// Generated by Haxe 5.0.0-preview.1
(function ($hx_exports, $global) { "use strict";
$hx_exports["hide"] = $hx_exports["hide"] || {};
$hx_exports["hide"]["presentation"] = $hx_exports["hide"]["presentation"] || {};
var $hxClasses = {},$estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
$hxClasses["EReg"] = EReg;
EReg.__name__ = "EReg";
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw haxe_Exception.thrown("EReg::matched");
		}
	}
	,__class__: EReg
};
var HxOverrides = function() { };
$hxClasses["HxOverrides"] = HxOverrides;
HxOverrides.__name__ = "HxOverrides";
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.now = function() {
	return Date.now();
};
var Lambda = function() { };
$hxClasses["Lambda"] = Lambda;
Lambda.__name__ = "Lambda";
Lambda.find = function(it,f) {
	var v = $getIterator(it);
	while(v.hasNext()) {
		var v1 = v.next();
		if(f(v1)) {
			return v1;
		}
	}
	return null;
};
Math.__name__ = "Math";
var Std = function() { };
$hxClasses["Std"] = Std;
Std.__name__ = "Std";
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var StringTools = function() { };
$hxClasses["StringTools"] = StringTools;
StringTools.__name__ = "StringTools";
StringTools.startsWith = function(s,start) {
	return s.length >= start.length && s.lastIndexOf(start,0) == 0;
};
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	return c > 8 && c < 14 || c == 32;
};
StringTools.trim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	var s1 = r > 0 ? HxOverrides.substr(s,0,l - r) : s;
	var l = s1.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s1,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s1,r,l - r);
	} else {
		return s1;
	}
};
var Type = function() { };
$hxClasses["Type"] = Type;
Type.__name__ = "Type";
Type.createInstance = function(cl,args) {
	var ctor = Function.prototype.bind.apply(cl,[null].concat(args));
	return new (ctor);
};
var electron_renderer_IpcRenderer = require("electron").ipcRenderer;
var haxe_StackItem = $hxEnums["haxe.StackItem"] = { __ename__:true,__constructs__:null
	,CFunction: {_hx_name:"CFunction",_hx_index:0,__enum__:"haxe.StackItem",toString:$estr}
	,Module: ($_=function(m) { return {_hx_index:1,m:m,__enum__:"haxe.StackItem",toString:$estr,__params__:function(){ return [this.m];}}; },$_._hx_name="Module",$_)
	,FilePos: ($_=function(s,file,line,column) { return {_hx_index:2,s:s,file:file,line:line,column:column,__enum__:"haxe.StackItem",toString:$estr,__params__:function(){ return [this.s,this.file,this.line,this.column];}}; },$_._hx_name="FilePos",$_)
	,Method: ($_=function(classname,method) { return {_hx_index:3,classname:classname,method:method,__enum__:"haxe.StackItem",toString:$estr,__params__:function(){ return [this.classname,this.method];}}; },$_._hx_name="Method",$_)
	,LocalFunction: ($_=function(v) { return {_hx_index:4,v:v,__enum__:"haxe.StackItem",toString:$estr,__params__:function(){ return [this.v];}}; },$_._hx_name="LocalFunction",$_)
};
haxe_StackItem.__constructs__ = [haxe_StackItem.CFunction,haxe_StackItem.Module,haxe_StackItem.FilePos,haxe_StackItem.Method,haxe_StackItem.LocalFunction];
var haxe_IMap = function() { };
$hxClasses["haxe.IMap"] = haxe_IMap;
haxe_IMap.__name__ = "haxe.IMap";
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
$hxClasses["haxe.Exception"] = haxe_Exception;
haxe_Exception.__name__ = "haxe.Exception";
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
	,toString: function() {
		return this.get_message();
	}
	,get_message: function() {
		return this.message;
	}
	,get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
$hxClasses["haxe.ValueException"] = haxe_ValueException;
haxe_ValueException.__name__ = "haxe.ValueException";
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
	,__class__: haxe_ValueException
});
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
$hxClasses["haxe.ds.StringMap"] = haxe_ds_StringMap;
haxe_ds_StringMap.__name__ = "haxe.ds.StringMap";
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	__class__: haxe_ds_StringMap
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
$hxClasses["haxe.iterators.ArrayIterator"] = haxe_iterators_ArrayIterator;
haxe_iterators_ArrayIterator.__name__ = "haxe.iterators.ArrayIterator";
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var hx_injection_Service = function() { };
$hxClasses["hx.injection.Service"] = hx_injection_Service;
hx_injection_Service.__name__ = "hx.injection.Service";
hx_injection_Service.prototype = {
	__class__: hx_injection_Service
};
var hide_application_commands_LoadProjectUseCase = function(fileSystem,eventBus) {
	this.fileSystem = fileSystem;
	this.eventBus = eventBus;
};
$hxClasses["hide.application.commands.LoadProjectUseCase"] = hide_application_commands_LoadProjectUseCase;
hide_application_commands_LoadProjectUseCase.__name__ = "hide.application.commands.LoadProjectUseCase";
hide_application_commands_LoadProjectUseCase.__interfaces__ = [hx_injection_Service];
hide_application_commands_LoadProjectUseCase.prototype = {
	execute: function(projectPath) {
		try {
			var content = this.fileSystem.readText(projectPath);
			var data = JSON.parse(content);
			var projectName = data.name != null ? data.name : "Unnamed Project";
			var project = new hide_domain_entities_Project("id-1",projectName,projectPath);
			this.eventBus.publish(hide_shared_events_ProjectLoaded,new hide_shared_events_ProjectLoaded(project));
			return hide_shared_types_Result.Success(project);
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			var errorMsg = Std.string(e);
			this.eventBus.publish(hide_shared_events_ErrorOccurred,new hide_shared_events_ErrorOccurred("LoadProjectUseCase",errorMsg));
			return hide_shared_types_Result.Failure(errorMsg);
		}
	}
	,getConstructorArgs: function() {
		return ["hide.domain.services.IFileSystem","hide.shared.types.IEventBus"];
	}
	,__class__: hide_application_commands_LoadProjectUseCase
};
var hide_application_commands_SetFullscreenUseCase = function(windowService,eventBus) {
	this.windowService = windowService;
	this.eventBus = eventBus;
};
$hxClasses["hide.application.commands.SetFullscreenUseCase"] = hide_application_commands_SetFullscreenUseCase;
hide_application_commands_SetFullscreenUseCase.__name__ = "hide.application.commands.SetFullscreenUseCase";
hide_application_commands_SetFullscreenUseCase.__interfaces__ = [hx_injection_Service];
hide_application_commands_SetFullscreenUseCase.prototype = {
	execute: function(enabled) {
		if(enabled) {
			this.windowService.enterFullscreen();
		} else {
			this.windowService.leaveFullscreen();
		}
		this.eventBus.publish(hide_shared_events_FullscreenChanged,new hide_shared_events_FullscreenChanged(enabled));
	}
	,getConstructorArgs: function() {
		return ["hide.application.services.WindowService","hide.shared.types.IEventBus"];
	}
	,__class__: hide_application_commands_SetFullscreenUseCase
};
var hide_application_services_MenuService = function() {
	this.menuItems = [];
	this.handlers = new haxe_ds_StringMap();
};
$hxClasses["hide.application.services.MenuService"] = hide_application_services_MenuService;
hide_application_services_MenuService.__name__ = "hide.application.services.MenuService";
hide_application_services_MenuService.__interfaces__ = [hx_injection_Service];
hide_application_services_MenuService.prototype = {
	onItemClick: function(id,handler) {
		this.handlers.h[id] = handler;
	}
	,addItem: function(id,label,icon) {
		this.menuItems.push({ id : id, label : label, icon : icon});
	}
	,addViewMenu: function(view) {
		var id = "view.${view.name}";
		this.addItem(id,view.label,view.icon);
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_application_services_MenuService
};
var hide_application_services_PluginManager = function(registry,viewRegistry,eventBus,fileSystem) {
	this.registry = registry;
	this.viewRegistry = viewRegistry;
	this.eventBus = eventBus;
	this.fileSystem = fileSystem;
	this.configPath = hide_domain_valueobjects_FilePath._hx_new("plugins.json");
	this.loadConfig();
};
$hxClasses["hide.application.services.PluginManager"] = hide_application_services_PluginManager;
hide_application_services_PluginManager.__name__ = "hide.application.services.PluginManager";
hide_application_services_PluginManager.__interfaces__ = [hx_injection_Service];
hide_application_services_PluginManager.prototype = {
	loadConfig: function() {
		if(this.fileSystem.exists(this.configPath)) {
			var content = this.fileSystem.readText(this.configPath);
			this.config = JSON.parse(content);
		} else {
			this.config = { plugins : []};
			this.saveConfig();
		}
	}
	,loadAll: function() {
		var _g = 0;
		var _g1 = this.config.plugins;
		while(_g < _g1.length) {
			var pluginConfig = _g1[_g];
			++_g;
			if(!pluginConfig.enabled) {
				continue;
			}
			if(this.registry.get(pluginConfig.name) != null) {
				continue;
			}
			try {
				var plugin = this.loadPlugin(pluginConfig);
				if(plugin != null && plugin.activate()) {
					this.registry.add(pluginConfig.name,plugin);
				} else if(plugin != null) {
					console.log("hide/application/services/PluginManager.hx:56:","Plugin " + pluginConfig.name + " activation returned false");
				}
			} catch( _g2 ) {
				var e = haxe_Exception.caught(_g2).unwrap();
				console.log("hide/application/services/PluginManager.hx:59:","Failed to load plugin: " + pluginConfig.name + " - " + Std.string(e));
			}
		}
	}
	,loadPlugin: function(pluginConfig) {
		var className = pluginConfig.className;
		var pluginClass = $hxClasses[className];
		if(pluginClass == null) {
			console.log("hide/application/services/PluginManager.hx:69:","Plugin class not found: " + className);
			return null;
		}
		try {
			var args = [this.viewRegistry,this.eventBus,pluginConfig.config != null ? pluginConfig.config : { }];
			var plugin = Type.createInstance(pluginClass,args);
			if(!js_Boot.__implements(plugin,hide_domain_services_IPlugin)) {
				console.log("hide/application/services/PluginManager.hx:79:","Plugin " + className + " does not implement IPlugin");
				return null;
			}
			return plugin;
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			console.log("hide/application/services/PluginManager.hx:84:","Failed to instantiate plugin " + className + ". Error: " + Std.string(e));
			return null;
		}
	}
	,saveConfig: function() {
		var jsonStr = JSON.stringify(this.config,null,"  ");
		this.fileSystem.writeText(this.configPath,jsonStr);
	}
	,getConstructorArgs: function() {
		return ["hide.application.services.PluginRegistry","hide.application.services.ViewRegistry","hide.shared.types.IEventBus","hide.domain.services.IFileSystem"];
	}
	,__class__: hide_application_services_PluginManager
};
var hide_application_services_PluginRegistry = function() {
	this.plugins = new haxe_ds_StringMap();
};
$hxClasses["hide.application.services.PluginRegistry"] = hide_application_services_PluginRegistry;
hide_application_services_PluginRegistry.__name__ = "hide.application.services.PluginRegistry";
hide_application_services_PluginRegistry.__interfaces__ = [hx_injection_Service];
hide_application_services_PluginRegistry.prototype = {
	add: function(name,plugin) {
		if(Object.prototype.hasOwnProperty.call(this.plugins.h,name)) {
			throw haxe_Exception.thrown("Plugin $name already exists");
		}
		this.plugins.h[name] = plugin;
	}
	,get: function(name) {
		return this.plugins.h[name];
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_application_services_PluginRegistry
};
var hide_application_services_ViewRegistry = function() {
	this.viewFactories = new haxe_ds_StringMap();
	this.views = [];
	this.add({ name : "editor", label : "Редактор", description : "Открыть редактор кода", icon : "fa-code", defaultState : { }});
	this.add({ name : "project", label : "Проект", description : "Показать дерево проекта", icon : "fa-folder", defaultState : { }});
};
$hxClasses["hide.application.services.ViewRegistry"] = hide_application_services_ViewRegistry;
hide_application_services_ViewRegistry.__name__ = "hide.application.services.ViewRegistry";
hide_application_services_ViewRegistry.__interfaces__ = [hx_injection_Service];
hide_application_services_ViewRegistry.prototype = {
	setFactoryRegistrationCallback: function(cb) {
		this.onFactoryRegistered = cb;
	}
	,registerViewFactory: function(name,factory) {
		this.viewFactories.h[name] = factory;
		if(this.onFactoryRegistered != null) {
			this.onFactoryRegistered(name,factory);
		}
	}
	,add: function(view) {
		if(this.find(view.name) != null) {
			throw haxe_Exception.thrown("View already exists: ${view.name}");
		}
		this.views.push(view);
	}
	,find: function(name) {
		return Lambda.find(this.views,function(v) {
			return v.name == name;
		});
	}
	,all: function() {
		return this.views.slice();
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_application_services_ViewRegistry
};
var hide_application_services_WindowService = function(manager) {
	this.isMaximized = false;
	this.isFullscreen = false;
	this.manager = manager;
	this.setupStateSync();
};
$hxClasses["hide.application.services.WindowService"] = hide_application_services_WindowService;
hide_application_services_WindowService.__name__ = "hide.application.services.WindowService";
hide_application_services_WindowService.__interfaces__ = [hx_injection_Service];
hide_application_services_WindowService.prototype = {
	setTitle: function(title) {
		this.manager.setTitle(title);
	}
	,enterFullscreen: function() {
		this.manager.enterFullscreen();
		this.isFullscreen = true;
		this.isMaximized = false;
	}
	,leaveFullscreen: function() {
		this.manager.leaveFullscreen();
		this.isFullscreen = false;
	}
	,setupStateSync: function() {
		var _gthis = this;
		this.manager.on(hide_domain_enums_WindowEvent.Maximize,function(_) {
			_gthis.isMaximized = true;
			_gthis.isFullscreen = false;
		});
		this.manager.on(hide_domain_enums_WindowEvent.Restore,function(_) {
			_gthis.isMaximized = false;
			_gthis.isFullscreen = false;
		});
		this.manager.on(hide_domain_enums_WindowEvent.FullscreenEnter,function(_) {
			_gthis.isFullscreen = true;
			_gthis.isMaximized = false;
		});
		this.manager.on(hide_domain_enums_WindowEvent.FullscreenLeave,function(_) {
			_gthis.isFullscreen = false;
		});
		this.manager.on(hide_domain_enums_WindowEvent.Move,function(_) {
		});
		this.manager.on(hide_domain_enums_WindowEvent.Resize,function(_) {
		});
	}
	,getConstructorArgs: function() {
		return ["hide.domain.services.IWindowManager"];
	}
	,__class__: hide_application_services_WindowService
};
var hide_domain_entities_Project = function(id,name,rootPath) {
	this.id = id;
	this.name = name;
	var tmp;
	if(hide_domain_valueobjects_FilePath.isValid(rootPath)) {
		tmp = rootPath;
	} else {
		throw haxe_Exception.thrown("Invalid path: " + rootPath);
	}
	this.rootPath = tmp;
	this.resources = new haxe_ds_StringMap();
	this._isDirty = false;
};
$hxClasses["hide.domain.entities.Project"] = hide_domain_entities_Project;
hide_domain_entities_Project.__name__ = "hide.domain.entities.Project";
hide_domain_entities_Project.prototype = {
	__class__: hide_domain_entities_Project
};
var hide_domain_entities_Resource = function() { };
$hxClasses["hide.domain.entities.Resource"] = hide_domain_entities_Resource;
hide_domain_entities_Resource.__name__ = "hide.domain.entities.Resource";
var hide_domain_enums_WindowEvent = $hxEnums["hide.domain.enums.WindowEvent"] = { __ename__:true,__constructs__:null
	,Focus: {_hx_name:"Focus",_hx_index:0,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Blur: {_hx_name:"Blur",_hx_index:1,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Resize: {_hx_name:"Resize",_hx_index:2,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Move: {_hx_name:"Move",_hx_index:3,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Maximize: {_hx_name:"Maximize",_hx_index:4,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Unmaximize: {_hx_name:"Unmaximize",_hx_index:5,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Minimize: {_hx_name:"Minimize",_hx_index:6,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Restore: {_hx_name:"Restore",_hx_index:7,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,Close: {_hx_name:"Close",_hx_index:8,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,FullscreenEnter: {_hx_name:"FullscreenEnter",_hx_index:9,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
	,FullscreenLeave: {_hx_name:"FullscreenLeave",_hx_index:10,__enum__:"hide.domain.enums.WindowEvent",toString:$estr}
};
hide_domain_enums_WindowEvent.__constructs__ = [hide_domain_enums_WindowEvent.Focus,hide_domain_enums_WindowEvent.Blur,hide_domain_enums_WindowEvent.Resize,hide_domain_enums_WindowEvent.Move,hide_domain_enums_WindowEvent.Maximize,hide_domain_enums_WindowEvent.Unmaximize,hide_domain_enums_WindowEvent.Minimize,hide_domain_enums_WindowEvent.Restore,hide_domain_enums_WindowEvent.Close,hide_domain_enums_WindowEvent.FullscreenEnter,hide_domain_enums_WindowEvent.FullscreenLeave];
var hide_domain_exceptions_FileNotFoundError = function(path) {
	haxe_Exception.call(this,"File not found: " + path.toString());
};
$hxClasses["hide.domain.exceptions.FileNotFoundError"] = hide_domain_exceptions_FileNotFoundError;
hide_domain_exceptions_FileNotFoundError.__name__ = "hide.domain.exceptions.FileNotFoundError";
hide_domain_exceptions_FileNotFoundError.__super__ = haxe_Exception;
hide_domain_exceptions_FileNotFoundError.prototype = $extend(haxe_Exception.prototype,{
	__class__: hide_domain_exceptions_FileNotFoundError
});
var hide_domain_services_IElement = function() { };
$hxClasses["hide.domain.services.IElement"] = hide_domain_services_IElement;
hide_domain_services_IElement.__name__ = "hide.domain.services.IElement";
hide_domain_services_IElement.prototype = {
	__class__: hide_domain_services_IElement
};
var hide_domain_services_IFileDialog = function() { };
$hxClasses["hide.domain.services.IFileDialog"] = hide_domain_services_IFileDialog;
hide_domain_services_IFileDialog.__name__ = "hide.domain.services.IFileDialog";
hide_domain_services_IFileDialog.__interfaces__ = [hx_injection_Service];
hide_domain_services_IFileDialog.prototype = {
	__class__: hide_domain_services_IFileDialog
};
var hide_domain_services_IFileSystem = function() { };
$hxClasses["hide.domain.services.IFileSystem"] = hide_domain_services_IFileSystem;
hide_domain_services_IFileSystem.__name__ = "hide.domain.services.IFileSystem";
hide_domain_services_IFileSystem.__interfaces__ = [hx_injection_Service];
hide_domain_services_IFileSystem.prototype = {
	__class__: hide_domain_services_IFileSystem
};
var hide_domain_services_ILayoutEngine = function() { };
$hxClasses["hide.domain.services.ILayoutEngine"] = hide_domain_services_ILayoutEngine;
hide_domain_services_ILayoutEngine.__name__ = "hide.domain.services.ILayoutEngine";
hide_domain_services_ILayoutEngine.__interfaces__ = [hx_injection_Service];
hide_domain_services_ILayoutEngine.prototype = {
	__class__: hide_domain_services_ILayoutEngine
};
var hide_domain_services_IPlatform = function() { };
$hxClasses["hide.domain.services.IPlatform"] = hide_domain_services_IPlatform;
hide_domain_services_IPlatform.__name__ = "hide.domain.services.IPlatform";
hide_domain_services_IPlatform.__interfaces__ = [hx_injection_Service];
hide_domain_services_IPlatform.prototype = {
	__class__: hide_domain_services_IPlatform
};
var hide_domain_services_IPlugin = function() { };
$hxClasses["hide.domain.services.IPlugin"] = hide_domain_services_IPlugin;
hide_domain_services_IPlugin.__name__ = "hide.domain.services.IPlugin";
hide_domain_services_IPlugin.prototype = {
	__class__: hide_domain_services_IPlugin
};
var hide_domain_services_IViewFactory = function() { };
$hxClasses["hide.domain.services.IViewFactory"] = hide_domain_services_IViewFactory;
hide_domain_services_IViewFactory.__name__ = "hide.domain.services.IViewFactory";
hide_domain_services_IViewFactory.__interfaces__ = [hx_injection_Service];
hide_domain_services_IViewFactory.prototype = {
	__class__: hide_domain_services_IViewFactory
};
var hide_domain_services_IWindowManager = function() { };
$hxClasses["hide.domain.services.IWindowManager"] = hide_domain_services_IWindowManager;
hide_domain_services_IWindowManager.__name__ = "hide.domain.services.IWindowManager";
hide_domain_services_IWindowManager.__interfaces__ = [hx_injection_Service];
hide_domain_services_IWindowManager.prototype = {
	__class__: hide_domain_services_IWindowManager
};
var hide_domain_valueobjects_DisplayPosition = $hxEnums["hide.domain.valueobjects.DisplayPosition"] = { __ename__:true,__constructs__:null
	,Left: {_hx_name:"Left",_hx_index:0,__enum__:"hide.domain.valueobjects.DisplayPosition",toString:$estr}
	,Center: {_hx_name:"Center",_hx_index:1,__enum__:"hide.domain.valueobjects.DisplayPosition",toString:$estr}
	,Bottom: {_hx_name:"Bottom",_hx_index:2,__enum__:"hide.domain.valueobjects.DisplayPosition",toString:$estr}
	,Right: {_hx_name:"Right",_hx_index:3,__enum__:"hide.domain.valueobjects.DisplayPosition",toString:$estr}
	,MiddleColumnInternal: {_hx_name:"MiddleColumnInternal",_hx_index:4,__enum__:"hide.domain.valueobjects.DisplayPosition",toString:$estr}
};
hide_domain_valueobjects_DisplayPosition.__constructs__ = [hide_domain_valueobjects_DisplayPosition.Left,hide_domain_valueobjects_DisplayPosition.Center,hide_domain_valueobjects_DisplayPosition.Bottom,hide_domain_valueobjects_DisplayPosition.Right,hide_domain_valueobjects_DisplayPosition.MiddleColumnInternal];
var hide_domain_valueobjects_FilePath = {};
hide_domain_valueobjects_FilePath._hx_new = function(path) {
	if(path == null || StringTools.trim(path) == "") {
		throw haxe_Exception.thrown("FilePath cannot be null or empty");
	}
	return path;
};
hide_domain_valueobjects_FilePath.isValid = function(this1) {
	return this1 != null && this1.length > 0;
};
var hide_infrastructure_di_AppModule = function() { };
$hxClasses["hide.infrastructure.di.AppModule"] = hide_infrastructure_di_AppModule;
hide_infrastructure_di_AppModule.__name__ = "hide.infrastructure.di.AppModule";
hide_infrastructure_di_AppModule.configure = function(collection) {
	var implementation = hide_infrastructure_platform_electron_ElectronIpcBridge;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_domain_services_IFileSystem.__name__,hide_infrastructure_platform_electron_ElectronFileSystemAdapter);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_domain_services_IFileDialog.__name__,hide_infrastructure_platform_electron_ElectronFileDialogAdapter);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_domain_services_IWindowManager.__name__,hide_infrastructure_platform_electron_ElectronWindowAdapter);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_domain_services_IPlatform.__name__,hide_infrastructure_platform_electron_ElectronPlatformAdapter);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_domain_services_ILayoutEngine.__name__,hide_infrastructure_external_GoldenLayoutAdapter);
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,hide_shared_types_IEventBus.__name__,hide_shared_types_EventBusImpl);
	var implementation = hide_application_services_ViewRegistry;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_services_PluginRegistry;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_services_WindowService;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_services_MenuService;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_services_PluginManager;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_commands_LoadProjectUseCase;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_application_commands_SetFullscreenUseCase;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
	var implementation = hide_presentation_Ide;
	collection.handleServiceAdd(hx_injection_ServiceType.Singleton,implementation.__name__,implementation);
};
var hide_infrastructure_external_GoldenLayoutAdapter = function(eventBus,viewRegistry) {
	this.eventBus = eventBus;
	this.viewRegistry = viewRegistry;
	this.viewFactories = new haxe_ds_StringMap();
	this.onLayoutChangedCallbacks = [];
	viewRegistry.setFactoryRegistrationCallback($bind(this,this.registerView));
};
$hxClasses["hide.infrastructure.external.GoldenLayoutAdapter"] = hide_infrastructure_external_GoldenLayoutAdapter;
hide_infrastructure_external_GoldenLayoutAdapter.__name__ = "hide.infrastructure.external.GoldenLayoutAdapter";
hide_infrastructure_external_GoldenLayoutAdapter.__interfaces__ = [hx_injection_Service,hide_domain_services_ILayoutEngine];
hide_infrastructure_external_GoldenLayoutAdapter.prototype = {
	setContainer: function(el) {
		this.container = el;
	}
	,init: function(state) {
		if(this.container == null) {
			console.log("hide/infrastructure/external/GoldenLayoutAdapter.hx:39:","WARNING: GoldenLayout container not set. Call setContainer() first.");
			return;
		}
		var contentData = state.content;
		if(contentData == null || contentData.length == 0) {
			contentData = this.createDefaultSkeleton().content;
		}
		var goldenConfig = this.toGoldenConfig({ content : contentData, fullScreen : null});
		this.layout = new GoldenLayout(goldenConfig,this.container);
		var h = this.viewFactories.h;
		var _g_h = h;
		var _g_keys = Object.keys(h);
		var _g_length = _g_keys.length;
		var _g_current = 0;
		while(_g_current < _g_length) {
			var key = _g_keys[_g_current++];
			var _g_key = key;
			var _g_value = _g_h[key];
			var type = _g_key;
			var factory = _g_value;
			this.registerComponentInLayout(type,factory);
		}
		this.layout.init();
		this.layout.on("stateChanged",$bind(this,this.onStateChanged));
	}
	,onStateChanged: function() {
		this.eventBus.publish(hide_shared_events_LayoutChanged,new hide_shared_events_LayoutChanged());
		var _g = 0;
		var _g1 = this.onLayoutChangedCallbacks;
		while(_g < _g1.length) {
			var cb = _g1[_g];
			++_g;
			cb();
		}
	}
	,registerView: function(type,factory) {
		this.viewFactories.h[type] = factory;
		if(this.layout != null && this.layout.isInitialised) {
			this.registerComponentInLayout(type,factory);
		}
	}
	,registerComponentInLayout: function(type,factory) {
		this.layout.registerComponent(type,function(glContainer,state) {
			var element = new hide_infrastructure_external_HtmlElement(glContainer.getElement());
			factory.create(element,state);
		});
	}
	,createDefaultSkeleton: function() {
		return { content : [{ type : "row", componentName : null, componentState : null, id : null, width : null, height : null, content : [{ type : "stack", id : "left", width : 20, componentName : null, componentState : null, height : null, content : null},{ type : "column", id : "middle-column", width : 60, componentName : null, componentState : null, height : null, content : [{ type : "stack", id : "center", componentName : null, componentState : null, width : null, height : null, content : null},{ type : "stack", id : "bottom", height : 30, componentName : null, componentState : null, width : null, content : null}]},{ type : "stack", id : "right", width : 20, componentName : null, componentState : null, height : null, content : null}]}], fullScreen : null};
	}
	,toGoldenConfig: function(state) {
		var _g = [];
		var _g1 = 0;
		var _g2 = state.content;
		while(_g1 < _g2.length) {
			var item = _g2[_g1];
			++_g1;
			_g.push(this.toGoldenItem(item));
		}
		return { content : _g, settings : { reorderEnabled : true, constrainDragToHeader : true, showPopoutIcon : false, showMaximiseIcon : true}};
	}
	,toGoldenItem: function(item) {
		var glType;
		switch(item.type) {
		case "column":
			glType = "column";
			break;
		case "row":
			glType = "row";
			break;
		case "stack":
			glType = "stack";
			break;
		default:
			glType = "component";
		}
		var item1 = item.componentName;
		var item2 = item.componentState;
		var tmp;
		if(item.content != null) {
			var _g = [];
			var _g1 = 0;
			var _g2 = item.content;
			while(_g1 < _g2.length) {
				var i = _g2[_g1];
				++_g1;
				_g.push(this.toGoldenItem(i));
			}
			tmp = _g;
		} else {
			tmp = null;
		}
		return { type : glType, componentName : item1, componentState : item2, content : tmp, id : item.id, width : item.width, height : item.height, isClosable : true, title : null, activeItemIndex : null};
	}
	,getConstructorArgs: function() {
		return ["hide.shared.types.IEventBus","hide.application.services.ViewRegistry"];
	}
	,__class__: hide_infrastructure_external_GoldenLayoutAdapter
};
var hide_infrastructure_external_HtmlElement = function(element) {
	if(((element) instanceof HTMLElement)) {
		this.element = element;
	} else if(Object.prototype.hasOwnProperty.call(element,"get")) {
		this.element = element.get(0);
	} else {
		this.element = element;
	}
};
$hxClasses["hide.infrastructure.external.HtmlElement"] = hide_infrastructure_external_HtmlElement;
hide_infrastructure_external_HtmlElement.__name__ = "hide.infrastructure.external.HtmlElement";
hide_infrastructure_external_HtmlElement.__interfaces__ = [hide_domain_services_IElement];
hide_infrastructure_external_HtmlElement.prototype = {
	setInnerHtml: function(html) {
		this.element.innerHTML = html;
	}
	,__class__: hide_infrastructure_external_HtmlElement
};
var hide_infrastructure_external_StubConsoleFactory = function() {
};
$hxClasses["hide.infrastructure.external.StubConsoleFactory"] = hide_infrastructure_external_StubConsoleFactory;
hide_infrastructure_external_StubConsoleFactory.__name__ = "hide.infrastructure.external.StubConsoleFactory";
hide_infrastructure_external_StubConsoleFactory.__interfaces__ = [hx_injection_Service,hide_domain_services_IViewFactory];
hide_infrastructure_external_StubConsoleFactory.prototype = {
	create: function(container,state) {
		container.setInnerHtml("\n            <div style='padding:20px; color:#cccccc; background:#1e1e1e; height:100%; font-family: monospace;'>\n                <h2>🖥️ Console</h2>\n                <p>Console output will appear here.</p>\n            </div>\n        ");
		return null;
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_external_StubConsoleFactory
};
var hide_infrastructure_external_StubEditorFactory = function() {
};
$hxClasses["hide.infrastructure.external.StubEditorFactory"] = hide_infrastructure_external_StubEditorFactory;
hide_infrastructure_external_StubEditorFactory.__name__ = "hide.infrastructure.external.StubEditorFactory";
hide_infrastructure_external_StubEditorFactory.__interfaces__ = [hx_injection_Service,hide_domain_services_IViewFactory];
hide_infrastructure_external_StubEditorFactory.prototype = {
	create: function(container,state) {
		container.setInnerHtml("\n            <div style='padding:20px; color:#d4d4d4; background:#1e1e1e; height:100%; font-family: monospace;'>\n                <h2>📝 Stub Editor</h2>\n                <p>Здесь будет <b>Monaco Editor</b>.</p>\n                <p>Состояние: " + JSON.stringify(state) + "</p>\n            </div>\n        ");
		return null;
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_external_StubEditorFactory
};
var hide_infrastructure_external_StubProjectFactory = function() {
};
$hxClasses["hide.infrastructure.external.StubProjectFactory"] = hide_infrastructure_external_StubProjectFactory;
hide_infrastructure_external_StubProjectFactory.__name__ = "hide.infrastructure.external.StubProjectFactory";
hide_infrastructure_external_StubProjectFactory.__interfaces__ = [hide_domain_services_IViewFactory];
hide_infrastructure_external_StubProjectFactory.prototype = {
	create: function(container,state) {
		container.setInnerHtml("\n            <div style='padding:20px; color:#cccccc; background:#252526; height:100%; font-family: sans-serif;'>\n                <h2>📁 Project Tree</h2>\n                <ul>\n                    <li>📂 src/</li>\n                    <li>📄 Main.hx</li>\n                    <li>📄 project.json</li>\n                </ul>\n            </div>\n        ");
		return null;
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_external_StubProjectFactory
};
var hide_infrastructure_external_StubPropertiesFactory = function() {
};
$hxClasses["hide.infrastructure.external.StubPropertiesFactory"] = hide_infrastructure_external_StubPropertiesFactory;
hide_infrastructure_external_StubPropertiesFactory.__name__ = "hide.infrastructure.external.StubPropertiesFactory";
hide_infrastructure_external_StubPropertiesFactory.__interfaces__ = [hx_injection_Service,hide_domain_services_IViewFactory];
hide_infrastructure_external_StubPropertiesFactory.prototype = {
	create: function(container,state) {
		container.setInnerHtml("\n            <div style='padding:20px; color:#cccccc; background:#252526; height:100%; font-family: sans-serif;'>\n                <h2>⚙️ Properties</h2>\n                <p>Object properties will appear here.</p>\n            </div>\n        ");
		return null;
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_external_StubPropertiesFactory
};
var hide_infrastructure_platform_electron_ElectronFileDialogAdapter = function(ipcBridge) {
	this.ipcBridge = ipcBridge;
};
$hxClasses["hide.infrastructure.platform.electron.ElectronFileDialogAdapter"] = hide_infrastructure_platform_electron_ElectronFileDialogAdapter;
hide_infrastructure_platform_electron_ElectronFileDialogAdapter.__name__ = "hide.infrastructure.platform.electron.ElectronFileDialogAdapter";
hide_infrastructure_platform_electron_ElectronFileDialogAdapter.__interfaces__ = [hide_domain_services_IFileDialog];
hide_infrastructure_platform_electron_ElectronFileDialogAdapter.prototype = {
	showOpen: function(options) {
		var electronOptions = { properties : ["openFile"], filters : options != null && options.filters != null ? options.filters : []};
		return tink_core_Future.map(this.ipcBridge.invokeSafe("dialog:showOpen",electronOptions),function(result) {
			if(result == null || result.canceled || result.filePaths.length == 0) {
				return null;
			}
			return result.filePaths[0];
		});
	}
	,getConstructorArgs: function() {
		return ["hide.infrastructure.platform.electron.ElectronIpcBridge"];
	}
	,__class__: hide_infrastructure_platform_electron_ElectronFileDialogAdapter
};
var hide_infrastructure_platform_electron_ElectronFileSystemAdapter = function(ipcBridge) {
	this.ipcBridge = ipcBridge;
};
$hxClasses["hide.infrastructure.platform.electron.ElectronFileSystemAdapter"] = hide_infrastructure_platform_electron_ElectronFileSystemAdapter;
hide_infrastructure_platform_electron_ElectronFileSystemAdapter.__name__ = "hide.infrastructure.platform.electron.ElectronFileSystemAdapter";
hide_infrastructure_platform_electron_ElectronFileSystemAdapter.__interfaces__ = [hide_domain_services_IFileSystem];
hide_infrastructure_platform_electron_ElectronFileSystemAdapter.prototype = {
	exists: function(filePath) {
		return this.ipcBridge.invokeSync("fs:exists",filePath.toString());
	}
	,readText: function(filePath) {
		if(!this.exists(filePath)) {
			throw new hide_domain_exceptions_FileNotFoundError(filePath);
		}
		var result = this.ipcBridge.invokeSync("fs:readText",filePath.toString());
		if(result.error != null) {
			throw new hide_domain_exceptions_FileNotFoundError(filePath);
		}
		return result.content;
	}
	,writeText: function(filePath,content) {
		var result = this.ipcBridge.invokeSync("fs:writeText",{ path : filePath.toString(), content : content});
		if(result.error != null) {
			throw haxe_Exception.thrown("Failed to write file: " + filePath.toString());
		}
	}
	,getConstructorArgs: function() {
		return ["hide.infrastructure.platform.electron.ElectronIpcBridge"];
	}
	,__class__: hide_infrastructure_platform_electron_ElectronFileSystemAdapter
};
var hide_infrastructure_platform_electron_ElectronIpcBridge = function() {
};
$hxClasses["hide.infrastructure.platform.electron.ElectronIpcBridge"] = hide_infrastructure_platform_electron_ElectronIpcBridge;
hide_infrastructure_platform_electron_ElectronIpcBridge.__name__ = "hide.infrastructure.platform.electron.ElectronIpcBridge";
hide_infrastructure_platform_electron_ElectronIpcBridge.__interfaces__ = [hx_injection_Service];
hide_infrastructure_platform_electron_ElectronIpcBridge.prototype = {
	invokeSafe: function(channel,args) {
		return tink_core_Future.async(function(trigger) {
			var promise = electron_renderer_IpcRenderer.invoke(channel,args);
			promise.then(function(result) {
				trigger(result);
				return null;
			}).catch(function(err) {
				console.log("hide/infrastructure/platform/electron/ElectronIpcBridge.hx:51:","[IPC Error] " + channel + ": " + Std.string(err));
				trigger(null);
				return null;
			});
		});
	}
	,invokeSync: function(channel,args) {
		return electron_renderer_IpcRenderer.sendSync(channel,args);
	}
	,on: function(channel,callback) {
		electron_renderer_IpcRenderer.on(channel,function(event,data) {
			callback(data);
		});
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_platform_electron_ElectronIpcBridge
};
var hide_infrastructure_platform_electron_ElectronPlatformAdapter = function() {
};
$hxClasses["hide.infrastructure.platform.electron.ElectronPlatformAdapter"] = hide_infrastructure_platform_electron_ElectronPlatformAdapter;
hide_infrastructure_platform_electron_ElectronPlatformAdapter.__name__ = "hide.infrastructure.platform.electron.ElectronPlatformAdapter";
hide_infrastructure_platform_electron_ElectronPlatformAdapter.__interfaces__ = [hide_domain_services_IPlatform];
hide_infrastructure_platform_electron_ElectronPlatformAdapter.prototype = {
	getAppArgs: function() {
		var argv = process.argv;
		if(argv.length > 2) {
			return argv.slice(2);
		} else {
			return [];
		}
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_infrastructure_platform_electron_ElectronPlatformAdapter
};
var hide_infrastructure_platform_electron_ElectronWindowAdapter = function(ipcBridge) {
	this.ipcBridge = ipcBridge;
};
$hxClasses["hide.infrastructure.platform.electron.ElectronWindowAdapter"] = hide_infrastructure_platform_electron_ElectronWindowAdapter;
hide_infrastructure_platform_electron_ElectronWindowAdapter.__name__ = "hide.infrastructure.platform.electron.ElectronWindowAdapter";
hide_infrastructure_platform_electron_ElectronWindowAdapter.__interfaces__ = [hide_domain_services_IWindowManager];
hide_infrastructure_platform_electron_ElectronWindowAdapter.prototype = {
	setTitle: function(title) {
		this.ipcBridge.invokeSync("window:setTitle",title);
	}
	,enterFullscreen: function() {
		this.ipcBridge.invokeSync("window:enterFullscreen");
	}
	,leaveFullscreen: function() {
		this.ipcBridge.invokeSync("window:leaveFullscreen");
	}
	,on: function(event,callback) {
		var eventName;
		switch(event._hx_index) {
		case 0:
			eventName = "window:focus";
			break;
		case 1:
			eventName = "window:blur";
			break;
		case 2:
			eventName = "window:resize";
			break;
		case 3:
			eventName = "window:move";
			break;
		case 4:
			eventName = "window:maximize";
			break;
		case 5:
			eventName = "window:unmaximize";
			break;
		case 6:
			eventName = "window:minimize";
			break;
		case 7:
			eventName = "window:restore";
			break;
		case 8:
			eventName = "window:close";
			break;
		case 9:
			eventName = "window:fullscreen-enter";
			break;
		case 10:
			eventName = "window:fullscreen-leave";
			break;
		}
		this.ipcBridge.on(eventName,callback);
	}
	,getConstructorArgs: function() {
		return ["hide.infrastructure.platform.electron.ElectronIpcBridge"];
	}
	,__class__: hide_infrastructure_platform_electron_ElectronWindowAdapter
};
var hide_presentation_Ide = function(windowService,menuService,loadProjectUseCase,setFullscreenUseCase,viewRegistry,pluginManager,eventBus,fileDialog,platform,layoutEngine) {
	var _gthis = this;
	this.windowService = windowService;
	this.menuService = menuService;
	this.loadProjectUseCase = loadProjectUseCase;
	this.setFullscreenUseCase = setFullscreenUseCase;
	this.viewRegistry = viewRegistry;
	this.pluginManager = pluginManager;
	this.eventBus = eventBus;
	this.fileDialog = fileDialog;
	this.platform = platform;
	this.layoutEngine = layoutEngine;
	hide_presentation_Ide.inst = this;
	this.views = viewRegistry.all();
	var _g = 0;
	var _g1 = viewRegistry.all();
	while(_g < _g1.length) {
		var view = [_g1[_g]];
		++_g;
		menuService.addViewMenu(view[0]);
		menuService.onItemClick("view." + view[0].name,(function(view) {
			return function() {
				_gthis.openView(view[0].name);
			};
		})(view));
	}
	var statusEl = window.document.getElementById("status-bar");
	this.statusBar = new hide_presentation_ui_StatusBar(statusEl);
	this._projectLoadedUnsub = eventBus.subscribe(hide_shared_events_ProjectLoaded,$bind(this,this.onProjectLoadedHandler));
	this._errorUnsub = eventBus.subscribe(hide_shared_events_ErrorOccurred,$bind(this,this.onErrorOccurred));
	this._layoutChangedUnsub = eventBus.subscribe(hide_shared_events_LayoutChanged,function(e) {
		console.log("hide/presentation/Ide.hx:110:","Layout changed");
	});
	this._projectClosedUnsub = eventBus.subscribe(hide_shared_events_ProjectClosed,function(e) {
		_gthis._currentProject = null;
		_gthis.statusBar.showMessage("Project closed");
		_gthis.updateWindowTitle();
	});
};
$hxClasses["hide.presentation.Ide"] = hide_presentation_Ide;
$hx_exports["hide"]["presentation"]["Ide"] = hide_presentation_Ide;
hide_presentation_Ide.__name__ = "hide.presentation.Ide";
hide_presentation_Ide.__interfaces__ = [hx_injection_Service];
hide_presentation_Ide.main = function() {
	var collection = new hx_injection_ServiceCollection();
	hide_infrastructure_di_AppModule.configure(collection);
	var provider = collection.createProvider();
	var service = hide_presentation_Ide;
	var ide = provider.handleGetService(service.__name__,service,null);
	ide.startup();
	var service = hide_application_services_PluginManager;
	provider.handleGetService(service.__name__,service,null).loadAll();
};
hide_presentation_Ide.prototype = {
	onMenuOpenProject: function() {
		var _gthis = this;
		this.fileDialog.showOpen({ filters : [{ name : "Project Files", extensions : ["json","hide"]}]}).handle(function(path) {
			if(path != null) {
				var result = _gthis.loadProjectUseCase.execute(hide_domain_valueobjects_FilePath._hx_new(path));
				switch(result._hx_index) {
				case 0:
					console.log("hide/presentation/Ide.hx:126:","Project loading initiated successfully.");
					break;
				case 1:
					var err = result.error;
					_gthis.statusBar.setError("Failed to load project: " + err);
					break;
				}
			}
		});
	}
	,onErrorOccurred: function(event) {
		console.log("hide/presentation/Ide.hx:135:","UI ERROR [" + event.context + "]: " + Std.string(event.error));
	}
	,onProjectLoadedHandler: function(event) {
		this._currentProject = event.project.name;
		console.log("hide/presentation/Ide.hx:140:","UI: Project loaded successfully: " + this._currentProject);
		this.updateWindowTitle();
	}
	,onToggleFullscreen: function() {
		this.setFullscreenUseCase.execute(!this.windowService.isFullscreen);
	}
	,onLayoutSave: function() {
	}
	,onCloseProject: function() {
	}
	,onMenuItemClick: function(id) {
		switch(id) {
		case "help.about":
			this.showAboutDialog();
			break;
		case "layout.save":
			this.onLayoutSave();
			break;
		case "project.close":
			this.onCloseProject();
			break;
		case "project.open":
			this.onMenuOpenProject();
			break;
		case "view.editor":
			this.openView("editor");
			break;
		case "view.fullscreen":
			this.onToggleFullscreen();
			break;
		case "view.project":
			this.openView("project");
			break;
		default:
			if(StringTools.startsWith(id,"project.recents.")) {
				var path = HxOverrides.substr(id,"project.recents.".length,null);
				this.onOpenRecent(path);
			} else {
				console.log("hide/presentation/Ide.hx:175:","Unknown menu item ID: " + id);
			}
		}
	}
	,openView: function(viewName) {
		var view = Lambda.find(this.views,function(v) {
			return v.name == viewName;
		});
		if(view == null) {
			throw haxe_Exception.thrown("View not found: " + viewName);
		}
		var position;
		switch(viewName) {
		case "editor":
			position = hide_domain_valueobjects_DisplayPosition.Center;
			break;
		case "project":
			position = hide_domain_valueobjects_DisplayPosition.Left;
			break;
		default:
			position = hide_domain_valueobjects_DisplayPosition.Center;
		}
	}
	,onOpenRecent: function(path) {
		this.loadProjectUseCase.execute(hide_domain_valueobjects_FilePath._hx_new(path));
	}
	,updateWindowTitle: function() {
		var title = this._currentProject != null ? "" + this._currentProject + " - HIDE IDE" : "HIDE IDE";
		console.log("hide/presentation/Ide.hx:202:","Window title updated to: " + title);
		this.windowService.setTitle(title);
	}
	,showAboutDialog: function() {
		console.log("hide/presentation/Ide.hx:207:","HIDE IDE\nVersion 0.1.0");
	}
	,get_currentProjectName: function() {
		if(this._currentProject != null) {
			return this._currentProject;
		} else {
			return "No project";
		}
	}
	,startup: function() {
		console.log("hide/presentation/Ide.hx:227:","✅ DI Контейнер успешно инициализирован! Ide создан.");
		this.viewRegistry.registerViewFactory("project",new hide_infrastructure_external_StubProjectFactory());
		this.viewRegistry.registerViewFactory("editor",new hide_infrastructure_external_StubEditorFactory());
		this.viewRegistry.registerViewFactory("console",new hide_infrastructure_external_StubConsoleFactory());
		this.viewRegistry.registerViewFactory("properties",new hide_infrastructure_external_StubPropertiesFactory());
		var layoutEl = window.document.getElementById("golden-layout-root");
		if(layoutEl != null) {
			this.layoutEngine.setContainer(layoutEl);
			this.layoutEngine.init({ content : [], fullScreen : null});
			console.log("hide/presentation/Ide.hx:241:","🎨 GoldenLayout инициализирован.");
		} else {
			console.log("hide/presentation/Ide.hx:243:","❌ Element #golden-layout-root not found in DOM! Проверьте app.html.");
		}
		var args = this.platform.getAppArgs();
		var projectFile = null;
		var _g = 0;
		while(_g < args.length) {
			var arg = args[_g];
			++_g;
			if(arg != "" && !StringTools.startsWith(arg,"-") && !StringTools.startsWith(arg,"chrome://")) {
				projectFile = arg;
				break;
			}
		}
		if(projectFile != null) {
			console.log("hide/presentation/Ide.hx:260:","📂 Загрузка проекта из аргумента командной строки: " + projectFile);
			this.loadProjectUseCase.execute(hide_domain_valueobjects_FilePath._hx_new(projectFile));
		} else {
			console.log("hide/presentation/Ide.hx:263:","👋 Приложение запущено без проекта.");
		}
	}
	,dispose: function() {
		if(this._projectLoadedUnsub != null) {
			var this1 = this._projectLoadedUnsub;
			if(this1 != null) {
				this1.cancel();
			}
		}
		if(this._errorUnsub != null) {
			var this1 = this._errorUnsub;
			if(this1 != null) {
				this1.cancel();
			}
		}
		if(this._layoutChangedUnsub != null) {
			var this1 = this._layoutChangedUnsub;
			if(this1 != null) {
				this1.cancel();
			}
		}
		if(this._projectClosedUnsub != null) {
			var this1 = this._projectClosedUnsub;
			if(this1 != null) {
				this1.cancel();
			}
		}
	}
	,getConstructorArgs: function() {
		return ["hide.application.services.WindowService","hide.application.services.MenuService","hide.application.commands.LoadProjectUseCase","hide.application.commands.SetFullscreenUseCase","hide.application.services.ViewRegistry","hide.application.services.PluginManager","hide.shared.types.IEventBus","hide.domain.services.IFileDialog","hide.domain.services.IPlatform","hide.domain.services.ILayoutEngine"];
	}
	,__class__: hide_presentation_Ide
};
var hide_presentation_ui_StatusBar = function(element) {
	this.element = element;
};
$hxClasses["hide.presentation.ui.StatusBar"] = hide_presentation_ui_StatusBar;
hide_presentation_ui_StatusBar.__name__ = "hide.presentation.ui.StatusBar";
hide_presentation_ui_StatusBar.prototype = {
	showMessage: function(msg) {
		console.log("hide/presentation/ui/StatusBar.hx:11:","[StatusBar] " + msg);
	}
	,setError: function(msg) {
		console.log("hide/presentation/ui/StatusBar.hx:15:","[StatusBar ERROR] " + msg);
	}
	,__class__: hide_presentation_ui_StatusBar
};
var hide_shared_events_ErrorOccurred = function(context,error) {
	this.context = context;
	this.error = error;
};
$hxClasses["hide.shared.events.ErrorOccurred"] = hide_shared_events_ErrorOccurred;
hide_shared_events_ErrorOccurred.__name__ = "hide.shared.events.ErrorOccurred";
hide_shared_events_ErrorOccurred.prototype = {
	__class__: hide_shared_events_ErrorOccurred
};
var hide_shared_events_FullscreenChanged = function(enabled) {
	this.enabled = enabled;
};
$hxClasses["hide.shared.events.FullscreenChanged"] = hide_shared_events_FullscreenChanged;
hide_shared_events_FullscreenChanged.__name__ = "hide.shared.events.FullscreenChanged";
hide_shared_events_FullscreenChanged.prototype = {
	__class__: hide_shared_events_FullscreenChanged
};
var hide_shared_events_LayoutChanged = function() {
};
$hxClasses["hide.shared.events.LayoutChanged"] = hide_shared_events_LayoutChanged;
hide_shared_events_LayoutChanged.__name__ = "hide.shared.events.LayoutChanged";
hide_shared_events_LayoutChanged.prototype = {
	__class__: hide_shared_events_LayoutChanged
};
var hide_shared_events_ProjectClosed = function() { };
$hxClasses["hide.shared.events.ProjectClosed"] = hide_shared_events_ProjectClosed;
hide_shared_events_ProjectClosed.__name__ = "hide.shared.events.ProjectClosed";
var hide_shared_events_ProjectLoaded = function(project) {
	this.project = project;
};
$hxClasses["hide.shared.events.ProjectLoaded"] = hide_shared_events_ProjectLoaded;
hide_shared_events_ProjectLoaded.__name__ = "hide.shared.events.ProjectLoaded";
hide_shared_events_ProjectLoaded.prototype = {
	__class__: hide_shared_events_ProjectLoaded
};
var hide_shared_types_IEventBus = function() { };
$hxClasses["hide.shared.types.IEventBus"] = hide_shared_types_IEventBus;
hide_shared_types_IEventBus.__name__ = "hide.shared.types.IEventBus";
hide_shared_types_IEventBus.__interfaces__ = [hx_injection_Service];
hide_shared_types_IEventBus.prototype = {
	__class__: hide_shared_types_IEventBus
};
var hide_shared_types_EventBusImpl = function() {
	this.handlers = new haxe_ds_StringMap();
};
$hxClasses["hide.shared.types.EventBusImpl"] = hide_shared_types_EventBusImpl;
hide_shared_types_EventBusImpl.__name__ = "hide.shared.types.EventBusImpl";
hide_shared_types_EventBusImpl.__interfaces__ = [hide_shared_types_IEventBus];
hide_shared_types_EventBusImpl.prototype = {
	subscribe: function(eventClass,handler) {
		var typeName = eventClass.__name__;
		var list = this.handlers.h[typeName];
		if(list == null) {
			list = [];
			this.handlers.h[typeName] = list;
		}
		var typedHandler = handler;
		list.push(typedHandler);
		return new tink_core_SimpleLink(function() {
			HxOverrides.remove(list,typedHandler);
		});
	}
	,publish: function(eventClass,event) {
		var typeName = eventClass.__name__;
		var list = this.handlers.h[typeName];
		if(list != null) {
			var snapshot = list.slice();
			var _g = 0;
			while(_g < snapshot.length) {
				var h = snapshot[_g];
				++_g;
				h(event);
			}
		}
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hide_shared_types_EventBusImpl
};
var hide_shared_types_Result = $hxEnums["hide.shared.types.Result"] = { __ename__:true,__constructs__:null
	,Success: ($_=function(value) { return {_hx_index:0,value:value,__enum__:"hide.shared.types.Result",toString:$estr,__params__:function(){ return [this.value];}}; },$_._hx_name="Success",$_)
	,Failure: ($_=function(error) { return {_hx_index:1,error:error,__enum__:"hide.shared.types.Result",toString:$estr,__params__:function(){ return [this.error];}}; },$_._hx_name="Failure",$_)
};
hide_shared_types_Result.__constructs__ = [hide_shared_types_Result.Success,hide_shared_types_Result.Failure];
var hx_injection_Destructable = function() { };
$hxClasses["hx.injection.Destructable"] = hx_injection_Destructable;
hx_injection_Destructable.__name__ = "hx.injection.Destructable";
var hx_injection_InternalServiceType = $hxEnums["hx.injection.InternalServiceType"] = { __ename__:true,__constructs__:null
	,Singleton: ($_=function(implementation) { return {_hx_index:0,implementation:implementation,__enum__:"hx.injection.InternalServiceType",toString:$estr,__params__:function(){ return [this.implementation];}}; },$_._hx_name="Singleton",$_)
	,Transient: ($_=function(implementation) { return {_hx_index:1,implementation:implementation,__enum__:"hx.injection.InternalServiceType",toString:$estr,__params__:function(){ return [this.implementation];}}; },$_._hx_name="Transient",$_)
	,Scoped: ($_=function(implementation) { return {_hx_index:2,implementation:implementation,__enum__:"hx.injection.InternalServiceType",toString:$estr,__params__:function(){ return [this.implementation];}}; },$_._hx_name="Scoped",$_)
};
hx_injection_InternalServiceType.__constructs__ = [hx_injection_InternalServiceType.Singleton,hx_injection_InternalServiceType.Transient,hx_injection_InternalServiceType.Scoped];
var hx_injection_ServiceCollection = function() {
	this._configs = new haxe_ds_StringMap();
	this._requestedServices = new haxe_ds_StringMap();
	this._instancedServices = new haxe_ds_StringMap();
};
$hxClasses["hx.injection.ServiceCollection"] = hx_injection_ServiceCollection;
hx_injection_ServiceCollection.__name__ = "hx.injection.ServiceCollection";
hx_injection_ServiceCollection.prototype = {
	handleServiceAdd: function(type,name,implementation) {
		var serviceName = name;
		var implementationName = implementation.__name__;
		var implementationType;
		switch(type._hx_index) {
		case 0:
			implementationType = hx_injection_InternalServiceType.Singleton(implementationName);
			break;
		case 1:
			implementationType = hx_injection_InternalServiceType.Transient(implementationName);
			break;
		case 2:
			implementationType = hx_injection_InternalServiceType.Scoped(implementationName);
			break;
		}
		var definition = this.initialiseDefinition(serviceName);
		definition.add(implementationType);
		return new hx_injection_ServiceConfig(definition,implementation.__name__,implementationType);
	}
	,createProvider: function() {
		this.handleServiceAdd(hx_injection_ServiceType.Singleton,hx_injection_ServiceProvider.__name__,hx_injection_ServiceProvider);
		var provider = new hx_injection_ServiceProvider(this._configs,this._requestedServices,this._instancedServices);
		return provider;
	}
	,initialiseDefinition: function(type) {
		var definition = this._requestedServices.h[type];
		if(definition == null) {
			definition = new hx_injection_ServiceDefinition();
			this._requestedServices.h[type] = definition;
		}
		return definition;
	}
	,__class__: hx_injection_ServiceCollection
};
var hx_injection_ServiceConfig = function(definition,type,implementation) {
	this._definition = definition;
	this._type = type;
	this._implementation = implementation;
};
$hxClasses["hx.injection.ServiceConfig"] = hx_injection_ServiceConfig;
hx_injection_ServiceConfig.__name__ = "hx.injection.ServiceConfig";
hx_injection_ServiceConfig.prototype = {
	__class__: hx_injection_ServiceConfig
};
var hx_injection_ServiceGroup = function() { };
$hxClasses["hx.injection.ServiceGroup"] = hx_injection_ServiceGroup;
hx_injection_ServiceGroup.__name__ = "hx.injection.ServiceGroup";
hx_injection_ServiceGroup.prototype = {
	__class__: hx_injection_ServiceGroup
};
var hx_injection_ServiceDefinition = function() {
	this._bindings = new haxe_ds_StringMap();
	this._services = [];
};
$hxClasses["hx.injection.ServiceDefinition"] = hx_injection_ServiceDefinition;
hx_injection_ServiceDefinition.__name__ = "hx.injection.ServiceDefinition";
hx_injection_ServiceDefinition.__interfaces__ = [hx_injection_ServiceGroup];
hx_injection_ServiceDefinition.prototype = {
	add: function(type) {
		this._services.push(type);
	}
	,getServices: function() {
		return this._services;
	}
	,getServiceAtKey: function(key) {
		return this._services[this._bindings.h[key]];
	}
	,__class__: hx_injection_ServiceDefinition
};
var hx_injection_ServiceProvider = function(configs,services,instances) {
	this._requestedConfigs = configs;
	this._requestedServices = services;
	this._requestedInstances = instances;
	this._resolvedSingletonOrder = [];
	this._resolvedSingletons = new haxe_ds_StringMap();
	this._resolvedScopeOrder = [];
	this._resolvedScopes = new haxe_ds_StringMap();
	this.registerSelf();
};
$hxClasses["hx.injection.ServiceProvider"] = hx_injection_ServiceProvider;
hx_injection_ServiceProvider.__name__ = "hx.injection.ServiceProvider";
hx_injection_ServiceProvider.__interfaces__ = [hx_injection_Service,hx_injection_Destructable];
hx_injection_ServiceProvider.prototype = {
	registerSelf: function() {
		var name = hx_injection_ServiceProvider.__name__;
		this._resolvedSingletonOrder.push(name);
		this._resolvedSingletons.h[name] = this;
	}
	,handleGetService: function(name,service,binding) {
		var serviceName = name;
		var instance = this._requestedInstances.h[name];
		if(instance != null) {
			return instance;
		}
		var requestedGroup = this._requestedServices.h[serviceName];
		var requestedService = null;
		if(binding == null) {
			requestedService = requestedGroup.getServices()[0];
		} else {
			requestedService = requestedGroup.getServiceAtKey(binding.__name__);
		}
		if(requestedService == null) {
			throw new haxe_Exception("Service of type '" + serviceName + "' not found.");
		}
		var implementation = this.handleServiceRequest(serviceName,requestedService);
		return implementation;
	}
	,handleServiceRequest: function(name,serviceType) {
		switch(serviceType._hx_index) {
		case 0:
			var implementation = serviceType.implementation;
			return this.handleSingletonService(name,implementation);
		case 1:
			var implementation = serviceType.implementation;
			return this.handleTransientService(name,implementation);
		case 2:
			var implementation = serviceType.implementation;
			return this.handleScopedService(name,implementation);
		}
	}
	,handleSingletonService: function(name,implementation) {
		var instance = this.getSingleton(implementation);
		if(instance == null) {
			instance = this.buildDependencyTree(name,implementation);
			this._resolvedSingletonOrder.splice(0,0,implementation);
			this._resolvedSingletons.h[implementation] = instance;
		}
		return instance;
	}
	,handleTransientService: function(name,implementation) {
		return this.buildDependencyTree(name,implementation);
	}
	,handleScopedService: function(name,implementation) {
		var instance = this.getScoped(implementation);
		if(instance == null) {
			instance = this.buildDependencyTree(name,implementation);
			this._resolvedScopeOrder.splice(0,0,implementation);
			this._resolvedScopes.h[implementation] = instance;
		}
		return instance;
	}
	,buildDependencyTree: function(name,service) {
		var dependencies = [];
		var args = this.getServiceArgs(service);
		var _g = 0;
		while(_g < args.length) {
			var arg = args[_g];
			++_g;
			var reg = new EReg("Iterable\\((.+)\\)","");
			var matched = reg.match(arg);
			if(matched) {
				var type = reg.matched(1);
				var dependencyArray = this.getRequestedService(type);
				if(dependencyArray != null) {
					var iterator = [];
					var _g1 = 0;
					while(_g1 < dependencyArray.length) {
						var dependency = dependencyArray[_g1];
						++_g1;
						var serviceInstance = this.handleServiceRequest(name,dependency);
						this.checkLifetimeInjection(name,dependency);
						iterator.push(serviceInstance);
					}
					dependencies.push(iterator);
					continue;
				}
			} else {
				var binding = arg.split("|");
				var serviceType = null;
				if(binding.length == 2) {
					serviceType = this.getBoundService(binding[0],binding[1]);
				} else {
					serviceType = this.getRequestedService(arg) != null ? this.getRequestedService(arg)[0] : null;
				}
				if(serviceType != null) {
					var serviceInstance1 = this.handleServiceRequest(name,serviceType);
					this.checkLifetimeInjection(name,serviceType);
					dependencies.push(serviceInstance1);
					continue;
				}
			}
			var config = this.getRequestedConfig(arg);
			if(config != null) {
				dependencies.push(config);
				continue;
			}
			throw new haxe_Exception("Dependency " + arg + " for " + service + " is missing. Did you add it to the collection?");
		}
		var cl = $hxClasses[service];
		if(cl != null) {
			return Type.createInstance(cl,dependencies);
		} else {
			throw new haxe_Exception("Cannot resolve " + service + " into a class.");
		}
	}
	,checkLifetimeInjection: function(name,next) {
		var group = this._requestedServices.h[name];
		var _g = 0;
		var _g1 = group.getServices();
		while(_g < _g1.length) {
			var service = _g1[_g];
			++_g;
			if(service._hx_index == 0) {
				var implementation = service.implementation;
				switch(next._hx_index) {
				case 1:
					var implementation1 = next.implementation;
					throw new haxe_Exception("Attempting to inject " + Std.string(next) + " into Singleton(" + name + ")");
				case 2:
					var implementation2 = next.implementation;
					throw new haxe_Exception("Attempting to inject " + Std.string(next) + " into Singleton(" + name + ")");
				default:
				}
			}
		}
	}
	,getServiceArgs: function(service) {
		var type = $hxClasses[service];
		var instance = Object.create(type.prototype);
		return instance.getConstructorArgs();
	}
	,getSingleton: function(serviceName) {
		return this._resolvedSingletons.h[serviceName];
	}
	,getScoped: function(serviceName) {
		return this._resolvedScopes.h[serviceName];
	}
	,getRequestedConfig: function(config) {
		return this._requestedConfigs.h[config];
	}
	,getRequestedService: function(serviceName) {
		var requested = this._requestedServices.h[serviceName];
		if(requested != null) {
			return requested.getServices();
		}
		return null;
	}
	,getBoundService: function(serviceName,key) {
		var requested = this._requestedServices.h[serviceName];
		return requested.getServiceAtKey(key);
	}
	,getConstructorArgs: function() {
		return [];
	}
	,__class__: hx_injection_ServiceProvider
};
var hx_injection_ServiceType = $hxEnums["hx.injection.ServiceType"] = { __ename__:true,__constructs__:null
	,Singleton: {_hx_name:"Singleton",_hx_index:0,__enum__:"hx.injection.ServiceType",toString:$estr}
	,Transient: {_hx_name:"Transient",_hx_index:1,__enum__:"hx.injection.ServiceType",toString:$estr}
	,Scoped: {_hx_name:"Scoped",_hx_index:2,__enum__:"hx.injection.ServiceType",toString:$estr}
};
hx_injection_ServiceType.__constructs__ = [hx_injection_ServiceType.Singleton,hx_injection_ServiceType.Transient,hx_injection_ServiceType.Scoped];
var js_Boot = function() { };
$hxClasses["js.Boot"] = js_Boot;
js_Boot.__name__ = "js.Boot";
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(o.__params__) {
				s = s + "\t";
				var params = o.__params__();
				var _g = 0;
				var _g1 = params.length;
				while(true) {
					if(!(_g < _g1)) {
						break;
					}
					var i = (function($this) {
						var $r;
						_g = _g + 1;
						$r = _g - 1;
						return $r;
					}(this));
					params[i] = js_Boot.__string_rec(params[i],s);
				}
				return (n == null ? "null" : "" + n) + "(" + params.join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__implements = function(o,iface) {
	return js_Boot.__interfLoop(js_Boot.getClass(o),iface);
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var tink_core_Callback = {};
tink_core_Callback.invoke = function(this1,data) {
	if(tink_core_Callback.depth < 500) {
		tink_core_Callback.depth++;
		this1(data);
		tink_core_Callback.depth--;
	} else {
		tink_core_Callback.defer(function() {
			this1(data);
		});
	}
};
tink_core_Callback.defer = function(f) {
	global.setImmediate(f);
};
var tink_core_LinkObject = function() { };
$hxClasses["tink.core.LinkObject"] = tink_core_LinkObject;
tink_core_LinkObject.__name__ = "tink.core.LinkObject";
tink_core_LinkObject.prototype = {
	__class__: tink_core_LinkObject
};
var tink_core_SimpleLink = function(f) {
	this.f = f;
};
$hxClasses["tink.core.SimpleLink"] = tink_core_SimpleLink;
tink_core_SimpleLink.__name__ = "tink.core.SimpleLink";
tink_core_SimpleLink.__interfaces__ = [tink_core_LinkObject];
tink_core_SimpleLink.prototype = {
	cancel: function() {
		if(this.f != null) {
			this.f();
			this.f = null;
		}
	}
	,__class__: tink_core_SimpleLink
};
var tink_core__$Callback_ListCell = function(cb,list) {
	if(cb == null) {
		throw haxe_Exception.thrown("callback expected but null received");
	}
	this.cb = cb;
	this.list = list;
};
$hxClasses["tink.core._Callback.ListCell"] = tink_core__$Callback_ListCell;
tink_core__$Callback_ListCell.__name__ = "tink.core._Callback.ListCell";
tink_core__$Callback_ListCell.__interfaces__ = [tink_core_LinkObject];
tink_core__$Callback_ListCell.prototype = {
	cancel: function() {
		if(this.list != null) {
			var list = this.list;
			this.cb = null;
			this.list = null;
			if(--list.used <= list.cells.length >> 1) {
				list.compact();
			}
		}
	}
	,__class__: tink_core__$Callback_ListCell
};
var tink_core_Disposable = function() { };
$hxClasses["tink.core.Disposable"] = tink_core_Disposable;
tink_core_Disposable.__name__ = "tink.core.Disposable";
var tink_core_OwnedDisposable = function() { };
$hxClasses["tink.core.OwnedDisposable"] = tink_core_OwnedDisposable;
tink_core_OwnedDisposable.__name__ = "tink.core.OwnedDisposable";
tink_core_OwnedDisposable.__interfaces__ = [tink_core_Disposable];
var tink_core_SimpleDisposable = function(dispose) {
	this.disposeHandlers = [];
	this.f = dispose;
};
$hxClasses["tink.core.SimpleDisposable"] = tink_core_SimpleDisposable;
tink_core_SimpleDisposable.__name__ = "tink.core.SimpleDisposable";
tink_core_SimpleDisposable.__interfaces__ = [tink_core_OwnedDisposable];
tink_core_SimpleDisposable.noop = function() {
};
tink_core_SimpleDisposable.prototype = {
	dispose: function() {
		var _g = this.disposeHandlers;
		if(_g != null) {
			var v = _g;
			this.disposeHandlers = null;
			var f = this.f;
			this.f = tink_core_SimpleDisposable.noop;
			f();
			var _g = 0;
			while(_g < v.length) {
				var h = v[_g];
				++_g;
				h();
			}
		}
	}
	,__class__: tink_core_SimpleDisposable
};
var tink_core_CallbackList = function(destructive) {
	if(destructive == null) {
		destructive = false;
	}
	this.onfill = function() {
	};
	this.ondrain = function() {
	};
	this.busy = false;
	this.queue = [];
	this.used = 0;
	var _gthis = this;
	tink_core_SimpleDisposable.call(this,function() {
		if(!_gthis.busy) {
			_gthis.destroy();
		}
	});
	this.destructive = destructive;
	this.cells = [];
};
$hxClasses["tink.core.CallbackList"] = tink_core_CallbackList;
tink_core_CallbackList.__name__ = "tink.core.CallbackList";
tink_core_CallbackList.__super__ = tink_core_SimpleDisposable;
tink_core_CallbackList.prototype = $extend(tink_core_SimpleDisposable.prototype,{
	destroy: function() {
		var _g = 0;
		var _g1 = this.cells;
		while(_g < _g1.length) {
			var c = _g1[_g];
			++_g;
			c.cb = null;
			c.list = null;
		}
		this.queue = null;
		this.cells = null;
		if(this.used > 0) {
			this.used = 0;
			var fn = this.ondrain;
			if(tink_core_Callback.depth < 500) {
				tink_core_Callback.depth++;
				fn();
				tink_core_Callback.depth--;
			} else {
				tink_core_Callback.defer(fn);
			}
		}
	}
	,invoke: function(data) {
		var _gthis = this;
		if(tink_core_Callback.depth < 500) {
			tink_core_Callback.depth++;
			if(_gthis.disposeHandlers != null) {
				if(_gthis.busy) {
					if(_gthis.destructive != true) {
						var _g = _gthis;
						var data1 = data;
						var tmp = function() {
							_g.invoke(data1);
						};
						_gthis.queue.push(tmp);
					}
				} else {
					_gthis.busy = true;
					if(_gthis.destructive) {
						_gthis.dispose();
					}
					var length = _gthis.cells.length;
					var _g1 = 0;
					var _g2 = length;
					while(_g1 < _g2) {
						var i = _g1++;
						var _this = _gthis.cells[i];
						if(_this.list != null) {
							_this.cb(data);
						}
					}
					_gthis.busy = false;
					if(_gthis.disposeHandlers == null) {
						_gthis.destroy();
					} else {
						if(_gthis.used < _gthis.cells.length) {
							_gthis.compact();
						}
						if(_gthis.queue.length > 0) {
							(_gthis.queue.shift())();
						}
					}
				}
			}
			tink_core_Callback.depth--;
		} else {
			tink_core_Callback.defer(function() {
				if(_gthis.disposeHandlers != null) {
					if(_gthis.busy) {
						if(_gthis.destructive != true) {
							var _g = _gthis;
							var data1 = data;
							var tmp = function() {
								_g.invoke(data1);
							};
							_gthis.queue.push(tmp);
						}
					} else {
						_gthis.busy = true;
						if(_gthis.destructive) {
							_gthis.dispose();
						}
						var length = _gthis.cells.length;
						var _g1 = 0;
						var _g2 = length;
						while(_g1 < _g2) {
							var i = _g1++;
							var _this = _gthis.cells[i];
							if(_this.list != null) {
								_this.cb(data);
							}
						}
						_gthis.busy = false;
						if(_gthis.disposeHandlers == null) {
							_gthis.destroy();
						} else {
							if(_gthis.used < _gthis.cells.length) {
								_gthis.compact();
							}
							if(_gthis.queue.length > 0) {
								(_gthis.queue.shift())();
							}
						}
					}
				}
			});
		}
	}
	,compact: function() {
		if(this.busy) {
			return;
		} else if(this.used == 0) {
			this.resize(0);
			var fn = this.ondrain;
			if(tink_core_Callback.depth < 500) {
				tink_core_Callback.depth++;
				fn();
				tink_core_Callback.depth--;
			} else {
				tink_core_Callback.defer(fn);
			}
		} else {
			var compacted = 0;
			var _g = 0;
			var _g1 = this.cells.length;
			while(_g < _g1) {
				var i = _g++;
				var _g2 = this.cells[i];
				if(_g2.cb != null) {
					var v = _g2;
					if(compacted != i) {
						this.cells[compacted] = v;
					}
					if(++compacted == this.used) {
						break;
					}
				}
			}
			this.resize(this.used);
		}
	}
	,resize: function(length) {
		this.cells.length = length;
	}
	,__class__: tink_core_CallbackList
});
var tink_core_TypedError = function(code,message,pos) {
	if(code == null) {
		code = 500;
	}
	this.code = code;
	this.message = message;
	this.pos = pos;
	this.exceptionStack = [];
	this.callStack = [];
};
$hxClasses["tink.core.TypedError"] = tink_core_TypedError;
tink_core_TypedError.__name__ = "tink.core.TypedError";
tink_core_TypedError.prototype = {
	printPos: function() {
		return this.pos.className + "." + this.pos.methodName + ":" + this.pos.lineNumber;
	}
	,toString: function() {
		var ret = "Error#" + this.code + ": " + this.message;
		if(this.pos != null) {
			ret += " @ " + this.printPos();
		}
		return ret;
	}
	,__class__: tink_core_TypedError
};
var tink_core__$Future_FutureObject = function() {
};
$hxClasses["tink.core._Future.FutureObject"] = tink_core__$Future_FutureObject;
tink_core__$Future_FutureObject.__name__ = "tink.core._Future.FutureObject";
tink_core__$Future_FutureObject.prototype = {
	getStatus: function() {
		return tink_core_FutureStatus.NeverEver;
	}
	,handle: function(callback) {
		return null;
	}
	,eager: function() {
	}
	,__class__: tink_core__$Future_FutureObject
};
var tink_core__$Lazy_Computable = function() { };
$hxClasses["tink.core._Lazy.Computable"] = tink_core__$Lazy_Computable;
tink_core__$Lazy_Computable.__name__ = "tink.core._Lazy.Computable";
tink_core__$Lazy_Computable.prototype = {
	__class__: tink_core__$Lazy_Computable
};
var tink_core__$Lazy_LazyObject = function() { };
$hxClasses["tink.core._Lazy.LazyObject"] = tink_core__$Lazy_LazyObject;
tink_core__$Lazy_LazyObject.__name__ = "tink.core._Lazy.LazyObject";
tink_core__$Lazy_LazyObject.__interfaces__ = [tink_core__$Lazy_Computable];
tink_core__$Lazy_LazyObject.prototype = {
	__class__: tink_core__$Lazy_LazyObject
};
var tink_core__$Lazy_LazyConst = function(value) {
	this.value = value;
};
$hxClasses["tink.core._Lazy.LazyConst"] = tink_core__$Lazy_LazyConst;
tink_core__$Lazy_LazyConst.__name__ = "tink.core._Lazy.LazyConst";
tink_core__$Lazy_LazyConst.__interfaces__ = [tink_core__$Lazy_LazyObject];
tink_core__$Lazy_LazyConst.prototype = {
	isComputed: function() {
		return true;
	}
	,get: function() {
		return this.value;
	}
	,compute: function() {
	}
	,underlying: function() {
		return null;
	}
	,__class__: tink_core__$Lazy_LazyConst
};
var tink_core__$Future_SyncFuture = function(value) {
	tink_core__$Future_FutureObject.call(this);
	this.value = value;
};
$hxClasses["tink.core._Future.SyncFuture"] = tink_core__$Future_SyncFuture;
tink_core__$Future_SyncFuture.__name__ = "tink.core._Future.SyncFuture";
tink_core__$Future_SyncFuture.__super__ = tink_core__$Future_FutureObject;
tink_core__$Future_SyncFuture.prototype = $extend(tink_core__$Future_FutureObject.prototype,{
	getStatus: function() {
		return tink_core_FutureStatus.Ready(this.value);
	}
	,handle: function(cb) {
		tink_core_Callback.invoke(cb,tink_core_Lazy.get(this.value));
		return null;
	}
	,eager: function() {
		if(!this.value.isComputed()) {
			tink_core_Lazy.get(this.value);
		}
	}
	,__class__: tink_core__$Future_SyncFuture
});
var tink_core_Future = {};
tink_core_Future.never = function() {
	return tink_core_Future.NEVER_INST;
};
tink_core_Future.map = function(this1,f,gather) {
	var _g = this1.getStatus();
	switch(_g._hx_index) {
	case 3:
		var l = _g.result;
		var this2 = l;
		var f1 = f;
		return new tink_core__$Future_SyncFuture(new tink_core__$Lazy_LazyFunc(function() {
			return f1(this2.get());
		},this2));
	case 4:
		return tink_core_Future.never();
	default:
		return new tink_core__$Future_SuspendableFuture(function($yield,_) {
			return this1.handle(function(v) {
				$yield(f(v));
			});
		});
	}
};
tink_core_Future.async = function(init,lazy) {
	if(lazy == null) {
		lazy = false;
	}
	var ret = tink_core_Future.irreversible(init);
	if(lazy) {
		return ret;
	} else {
		ret.eager();
		return ret;
	}
};
tink_core_Future.irreversible = function(init) {
	return new tink_core__$Future_SuspendableFuture(function($yield,_) {
		init($yield);
		return null;
	});
};
var tink_core_FutureStatus = $hxEnums["tink.core.FutureStatus"] = { __ename__:true,__constructs__:null
	,Suspended: {_hx_name:"Suspended",_hx_index:0,__enum__:"tink.core.FutureStatus",toString:$estr}
	,Awaited: {_hx_name:"Awaited",_hx_index:1,__enum__:"tink.core.FutureStatus",toString:$estr}
	,EagerlyAwaited: {_hx_name:"EagerlyAwaited",_hx_index:2,__enum__:"tink.core.FutureStatus",toString:$estr}
	,Ready: ($_=function(result) { return {_hx_index:3,result:result,__enum__:"tink.core.FutureStatus",toString:$estr,__params__:function(){ return [this.result];}}; },$_._hx_name="Ready",$_)
	,NeverEver: {_hx_name:"NeverEver",_hx_index:4,__enum__:"tink.core.FutureStatus",toString:$estr}
};
tink_core_FutureStatus.__constructs__ = [tink_core_FutureStatus.Suspended,tink_core_FutureStatus.Awaited,tink_core_FutureStatus.EagerlyAwaited,tink_core_FutureStatus.Ready,tink_core_FutureStatus.NeverEver];
var tink_core__$Future_SuspendableFuture = function(wakeup) {
	this.status = tink_core_FutureStatus.Suspended;
	var _gthis = this;
	tink_core__$Future_FutureObject.call(this);
	this.wakeup = wakeup;
	this.callbacks = new tink_core_CallbackList(true);
	this.callbacks.ondrain = function() {
		if(_gthis.status == tink_core_FutureStatus.Awaited) {
			_gthis.status = tink_core_FutureStatus.Suspended;
			var this1 = _gthis.link;
			if(this1 != null) {
				this1.cancel();
			}
			_gthis.link = null;
		}
	};
	this.callbacks.onfill = function() {
		if(_gthis.status == tink_core_FutureStatus.Suspended) {
			_gthis.status = tink_core_FutureStatus.Awaited;
			_gthis.arm();
		}
	};
};
$hxClasses["tink.core._Future.SuspendableFuture"] = tink_core__$Future_SuspendableFuture;
tink_core__$Future_SuspendableFuture.__name__ = "tink.core._Future.SuspendableFuture";
tink_core__$Future_SuspendableFuture.__super__ = tink_core__$Future_FutureObject;
tink_core__$Future_SuspendableFuture.prototype = $extend(tink_core__$Future_FutureObject.prototype,{
	getStatus: function() {
		return this.status;
	}
	,trigger: function(value) {
		if(this.status._hx_index != 3) {
			this.status = tink_core_FutureStatus.Ready(new tink_core__$Lazy_LazyConst(value));
			var link = this.link;
			this.link = null;
			this.wakeup = null;
			this.callbacks.invoke(value);
			if(link != null) {
				link.cancel();
			}
		}
	}
	,handle: function(callback) {
		var _g = this.status;
		if(_g._hx_index == 3) {
			var result = _g.result;
			tink_core_Callback.invoke(callback,tink_core_Lazy.get(result));
			return null;
		} else {
			var _this = this.callbacks;
			if(_this.disposeHandlers == null) {
				return null;
			} else {
				var node = new tink_core__$Callback_ListCell(callback,_this);
				_this.cells.push(node);
				if(_this.used++ == 0) {
					var fn = _this.onfill;
					if(tink_core_Callback.depth < 500) {
						tink_core_Callback.depth++;
						fn();
						tink_core_Callback.depth--;
					} else {
						tink_core_Callback.defer(fn);
					}
				}
				return node;
			}
		}
	}
	,destroy: function() {
		this.callbacks.dispose();
		this.status = tink_core_FutureStatus.NeverEver;
	}
	,arm: function() {
		var _gthis = this;
		this.link = this.wakeup(function(x) {
			_gthis.trigger(x);
		},$bind(this,this.destroy));
	}
	,eager: function() {
		switch(this.status._hx_index) {
		case 0:
			this.status = tink_core_FutureStatus.EagerlyAwaited;
			this.arm();
			break;
		case 1:
			this.status = tink_core_FutureStatus.EagerlyAwaited;
			break;
		default:
		}
	}
	,__class__: tink_core__$Future_SuspendableFuture
});
var tink_core_Lazy = {};
tink_core_Lazy.get = function(this1) {
	this1.compute();
	return this1.get();
};
var tink_core__$Lazy_LazyFunc = function(f,from) {
	this.busy = false;
	this.f = f;
	this.from = from;
};
$hxClasses["tink.core._Lazy.LazyFunc"] = tink_core__$Lazy_LazyFunc;
tink_core__$Lazy_LazyFunc.__name__ = "tink.core._Lazy.LazyFunc";
tink_core__$Lazy_LazyFunc.__interfaces__ = [tink_core__$Lazy_LazyObject];
tink_core__$Lazy_LazyFunc.prototype = {
	underlying: function() {
		return this.from;
	}
	,isComputed: function() {
		return this.f == null;
	}
	,get: function() {
		return this.result;
	}
	,compute: function() {
		if(this.busy) {
			throw haxe_Exception.thrown(new tink_core_TypedError(null,"circular lazyness",{ fileName : "tink/core/Lazy.hx", lineNumber : 85, className : "tink.core._Lazy.LazyFunc", methodName : "compute"}));
		}
		var _g = this.f;
		if(_g != null) {
			var v = _g;
			this.busy = true;
			this.f = null;
			var _g = this.from;
			if(_g != null) {
				var cur = _g;
				this.from = null;
				var stack = [];
				while(cur != null && !cur.isComputed()) {
					stack.push(cur);
					cur = cur.underlying();
				}
				stack.reverse();
				var _g = 0;
				while(_g < stack.length) {
					var c = stack[_g];
					++_g;
					c.compute();
				}
			}
			this.result = v();
			this.busy = false;
		}
	}
	,__class__: tink_core__$Lazy_LazyFunc
};
function $getIterator(o) { if( o instanceof Array ) return new haxe_iterators_ArrayIterator(o); else return o.iterator(); }
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
$hxClasses["Math"] = Math;
Object.defineProperty(String.prototype,"__class__",{ value : $hxClasses["String"] = String, enumerable : false, writable : true});
String.__name__ = "String";
$hxClasses["Array"] = Array;
Array.__name__ = "Array";
js_Boot.__toStr = ({ }).toString;
tink_core_Callback.depth = 0;
tink_core_Future.NEVER_INST = new tink_core__$Future_FutureObject();
hide_presentation_Ide.main();
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=app.js.map