// Generated by Haxe 4.3.0
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var Type = function() { };
Type.__name__ = true;
Type.createInstance = function(cl,args) {
	var ctor = Function.prototype.bind.apply(cl,[null].concat(args));
	return new (ctor);
};
var electron_renderer_IpcRenderer = require("electron").ipcRenderer;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var hide_core_Ide = function() {
	this.views = [];
	this.isInitialized = false;
	hide_core_Ide.inst = this;
	hide_core_IdeConfig.init();
	this.backend = hide_core_Ide.createBackend();
	this.backend.init();
	hide_core_IdeConfig.appPath = this.backend.getAppPath();
};
hide_core_Ide.__name__ = true;
hide_core_Ide.createBackend = function() {
	return new hide_electron_ElectronBackend();
};
hide_core_Ide.main = function() {
	window.onload = function() {
		console.log("hide/core/Ide.hx:474:","🌐 Renderer process starting...");
		window.document.getElementById("system-version").textContent = "🌐 Renderer process starting...";
		var app = new hide_core_Ide();
		app.init();
	};
};
hide_core_Ide.prototype = {
	open: function(component,state,onCreate,onOpen,positionOverride) {
		var _gthis = this;
		if(this.layout == null || this.layout.root == null) {
			console.log("hide/core/Ide.hx:78:","[Ide] ⚠️ Layout not ready");
			return;
		}
		if(state == null) {
			state = { };
		}
		var viewConfig = hide_ui_View.viewClasses.h[component];
		if(viewConfig == null) {
			throw haxe_Exception.thrown("Unknown component: " + component);
		}
		state.componentName = component;
		var _g = 0;
		var _g1 = this.views;
		while(_g < _g1.length) {
			var v = _g1[_g];
			++_g;
			if(v.viewClass == component && JSON.stringify(v.state) == JSON.stringify(state)) {
				v.activate();
				if(onCreate != null) {
					onCreate(v);
				}
				if(onOpen != null) {
					onOpen(v);
				}
				return;
			}
		}
		var options = viewConfig.options;
		var target = this.getOrInitTarget(positionOverride != null ? positionOverride : options.position);
		target.on("componentCreated",function(c) {
			target.off("componentCreated");
			var view = c.origin.__view;
			if(view != null) {
				_gthis.views.push(view);
				if(onCreate != null) {
					onCreate(view);
				}
				if(onOpen != null) {
					onOpen(view);
				}
			}
		});
		var config = { type : "component", componentName : component, componentState : state};
		if(options.id != null) {
			config.id = options.id;
		}
		target.addChild(config);
	}
	,getOrInitTarget: function(position) {
		return this.layout.root;
	}
	,getBackend: function() {
		return this.backend;
	}
	,init: function() {
		var _gthis = this;
		if(this.isInitialized) {
			return;
		}
		var _ = hide_view_CdbTable;
		console.log("hide/core/Ide.hx:287:","🚀 Hide IDE initializing...");
		this.windowManager = new hide_modules_WindowManager(this);
		this.menuSystem = new hide_modules_MenuSystem(this);
		this.menuSystem.loadFromXml();
		this.menuSystem.registerCommand("exit",function() {
			console.log("hide/core/Ide.hx:298:","🚪 Exit");
			_gthis.getBackend().quit();
		});
		this.menuSystem.registerCommand("open",function() {
			console.log("hide/core/Ide.hx:303:","📂 Open project");
		});
		this.menuSystem.registerCommand("clear",function() {
			console.log("hide/core/Ide.hx:308:","🗑 Clear recents");
		});
		this.menuSystem.registerCommand("clear-local",function() {
			console.log("hide/core/Ide.hx:313:","🧹 Clear local profile");
			window.localStorage.clear();
			_gthis.getBackend().clearCache();
			_gthis.getBackend().reload();
		});
		this.menuSystem.registerCommand("build-files",function() {
			console.log("hide/core/Ide.hx:320:","🔨 Build files");
		});
		this.menuSystem.registerCommand("debug",function() {
			console.log("hide/core/Ide.hx:326:","🐛 DevTools");
			_gthis.getBackend().showDevTools();
		});
		this.menuSystem.registerCommand("hide.view.FileBrowser",function() {
			_gthis.open("hide.view.FileBrowser",{ });
		});
		this.menuSystem.registerCommand("hide.view.DomkitStudio",function() {
			_gthis.open("hide.view.DomkitStudio",{ });
		});
		this.menuSystem.registerCommand("hide.view.About",function() {
			_gthis.open("hide.view.About",{ });
		});
		this.menuSystem.registerCommand("hide.view.Gym",function() {
			_gthis.open("hide.view.Gym",{ });
		});
		this.menuSystem.registerCommand("dbView",function() {
			_gthis.open("dbview.html",{ });
		});
		this.menuSystem.registerCommand("dbCustom",function() {
			console.log("hide/core/Ide.hx:351:","⚙️ DB Custom Types");
		});
		this.menuSystem.registerCommand("dbCompress",function() {
			console.log("hide/core/Ide.hx:354:","🗜 DB Compress toggle");
		});
		this.menuSystem.registerCommand("dbExport",function() {
			console.log("hide/core/Ide.hx:357:","📤 DB Export");
		});
		this.menuSystem.registerCommand("dbImport",function() {
			console.log("hide/core/Ide.hx:360:","📥 DB Import");
		});
		this.menuSystem.registerCommand("dbProofread",function() {
			console.log("hide/core/Ide.hx:363:","👁 DB Proofread toggle");
		});
		this.menuSystem.registerCommand("save",function() {
			console.log("hide/core/Ide.hx:368:","💾 Save layout");
		});
		this.menuSystem.registerCommand("saveas",function() {
			console.log("hide/core/Ide.hx:371:","💾 Save As...");
		});
		this.menuSystem.registerCommand("autosave",function() {
			console.log("hide/core/Ide.hx:374:","🔄 Autosave toggle");
		});
		this.menuSystem.registerCommand("user-settings",function() {
			console.log("hide/core/Ide.hx:379:","⚙️ User settings");
		});
		this.menuSystem.registerCommand("project-settings",function() {
			console.log("hide/core/Ide.hx:382:","⚙️ Project settings");
		});
		this.registerGoldenLayoutComponents();
		this.isInitialized = true;
		console.log("hide/core/Ide.hx:407:","✅ Hide IDE ready (stub mode).");
		window.document.getElementById("system-version").textContent = "✅ Hide IDE ready (stub mode).";
	}
	,registerGoldenLayoutComponents: function() {
		if(this.windowManager == null || this.windowManager.goldenLayout == null) {
			console.log("hide/core/Ide.hx:420:","[Ide] ⏳ GoldenLayout not ready yet (will register later)");
			return;
		}
		var gl = this.windowManager.goldenLayout;
		this.layout = gl;
		console.log("hide/core/Ide.hx:426:","[Ide] ✅ GoldenLayout connected, registering components...");
		var h = hide_ui_View.viewClasses.h;
		var componentName_h = h;
		var componentName_keys = Object.keys(h);
		var componentName_length = componentName_keys.length;
		var componentName_current = 0;
		while(componentName_current < componentName_length) {
			var componentName = componentName_keys[componentName_current++];
			var tmp = hide_ui_View.glFactory(componentName);
			gl.registerComponent(componentName,tmp);
			console.log("hide/core/Ide.hx:430:","[Ide] 📦 GL registered: " + componentName);
		}
	}
};
var hide_core_IdeConfig = function() { };
hide_core_IdeConfig.__name__ = true;
hide_core_IdeConfig.init = function() {
	hide_core_IdeConfig.isElectron = true;
	hide_core_IdeConfig.debugMode = true;
};
var hide_electron_ElectronBackend = function() {
	this.menuClickHandler = null;
};
hide_electron_ElectronBackend.__name__ = true;
hide_electron_ElectronBackend.prototype = {
	init: function() {
		var _gthis = this;
		console.log("hide/electron/ElectronBackend.hx:15:","[ElectronBackend] init()");
		electron_renderer_IpcRenderer.on("menu:click",function(event,data) {
			console.log("hide/electron/ElectronBackend.hx:19:","[ElectronBackend] 📥 menu:click received");
			if(_gthis.menuClickHandler != null && data != null && data.id != null) {
				_gthis.menuClickHandler(data.id);
			}
		});
		electron_renderer_IpcRenderer.on("app:clearCache:done",function(event,_) {
			console.log("hide/electron/ElectronBackend.hx:27:","[ElectronBackend] 🧹 Cache cleared");
			window.localStorage.clear();
		});
	}
	,createMenu: function(menuData) {
		var serialized = JSON.stringify(menuData);
		console.log("hide/electron/ElectronBackend.hx:56:","[ElectronBackend] 📤 Sending menu JSON: " + serialized);
		electron_renderer_IpcRenderer.send("menu:build",menuData);
	}
	,onMenuClick: function(handler) {
		console.log("hide/electron/ElectronBackend.hx:61:","[ElectronBackend] 📡 onMenuClick registered");
		this.menuClickHandler = handler;
	}
	,clearCache: function() {
		electron_renderer_IpcRenderer.send("app:clearCache");
	}
	,reload: function() {
		electron_renderer_IpcRenderer.send("app:reload");
	}
	,quit: function() {
		electron_renderer_IpcRenderer.send("app:quit");
	}
	,getAppPath: function() {
		return "./";
	}
	,showDevTools: function() {
		require('electron').remote.getCurrentWindow().webContents.openDevTools();
	}
};
var hide_modules_MenuSystem = function(ide) {
	this.ide = ide;
	this.commands = new haxe_ds_StringMap();
};
hide_modules_MenuSystem.__name__ = true;
hide_modules_MenuSystem.prototype = {
	loadFromXml: function() {
		var _gthis = this;
		var buildMenu = function() {
			var xmlEl = window.document.getElementById("mainmenu");
			if(xmlEl == null) {
				console.log("hide/modules/MenuSystem.hx:29:","[MenuSystem] ⚠️ mainmenu XML not found!");
				return;
			}
			var menuData = [];
			var _g = 0;
			var _g1 = xmlEl.children.length;
			while(_g < _g1) {
				var i = _g++;
				var item = _gthis.parseMenuItem(xmlEl.children[i]);
				if(item != null) {
					menuData.push(item);
				}
			}
			console.log("hide/modules/MenuSystem.hx:39:","[MenuSystem] 📤 Sending menu to Main: " + JSON.stringify(menuData));
			_gthis.ide.getBackend().createMenu(menuData);
			_gthis.ide.getBackend().onMenuClick($bind(_gthis,_gthis.handleCommand));
		};
		if(window.document.readyState == "complete" || window.document.readyState == "interactive") {
			buildMenu();
		} else {
			window.document.addEventListener("DOMContentLoaded",function(_) {
				buildMenu();
			});
		}
	}
	,registerCommand: function(id,handler) {
		this.commands.h[id] = handler;
		console.log("hide/modules/MenuSystem.hx:57:","[MenuSystem] ✅ Registered: " + id);
	}
	,handleCommand: function(id) {
		console.log("hide/modules/MenuSystem.hx:64:","[MenuSystem] 🔍 Command requested: '" + id + "'");
		if(Object.prototype.hasOwnProperty.call(this.commands.h,id)) {
			console.log("hide/modules/MenuSystem.hx:67:","[MenuSystem] ▶ Executing: " + id);
			this.commands.h[id]();
		} else {
			console.log("hide/modules/MenuSystem.hx:70:","[MenuSystem] ❌ Unknown command: '" + id + "'");
		}
	}
	,parseMenuItem: function(el) {
		var tag = el.tagName.toLowerCase();
		if(tag == "xml" || tag == "content") {
			return null;
		}
		if(tag == "separator") {
			return { label : "", type : "separator"};
		}
		if(tag == "div") {
			return { label : el.getAttribute("label") != null ? el.getAttribute("label") : "Section", enabled : false, submenu : []};
		}
		var label = el.getAttribute("label");
		if(label == null) {
			return null;
		}
		var cmd = null;
		if(el.getAttribute("class") != null) {
			cmd = el.getAttribute("class");
		} else if(el.getAttribute("onclick") != null) {
			cmd = el.getAttribute("onclick");
		} else if(el.getAttribute("id") != null) {
			cmd = el.getAttribute("id");
		} else if(el.getAttribute("command") != null) {
			cmd = el.getAttribute("command");
		}
		if(cmd != null) {
			cmd = StringTools.replace(cmd,"()","");
		}
		var type = el.getAttribute("type");
		var disabled = el.getAttribute("disabled") != null;
		var item = { label : label, id : cmd, type : type, enabled : !disabled};
		if(el.children != null && el.children.length > 0) {
			var submenu = [];
			var _g = 0;
			var _g1 = el.children.length;
			while(_g < _g1) {
				var i = _g++;
				var child = this.parseMenuItem(el.children[i]);
				if(child != null) {
					submenu.push(child);
				}
			}
			if(submenu.length > 0) {
				item.submenu = submenu;
			}
		}
		console.log("hide/modules/MenuSystem.hx:143:","[MenuSystem] Parsed: '" + label + "' → id='" + item.id + "'");
		return item;
	}
};
var hide_modules_WindowManager = function(ide) {
	this.goldenLayout = null;
	this.ide = ide;
};
hide_modules_WindowManager.__name__ = true;
var hide_ui_View = function(container,state,viewClass) {
	this.isActive = false;
	this.container = container;
	this.state = state;
	this.viewClass = viewClass;
	console.log("hide/ui/View.hx:41:","[View] 🎨 Creating: " + viewClass);
	this.element = window.document.createElement("div");
	var tmp = viewClass.split(".").pop();
	this.element.className = "hide-view hide-view-" + tmp;
	this.element.style.cssText = "width:100%;height:100%;display:flex;flex-direction:column;";
	container.getElement().appendChild(this.element);
	container.origin.__view = this;
	this.init();
};
hide_ui_View.__name__ = true;
hide_ui_View.register = function(componentName,cls,options) {
	if(Object.prototype.hasOwnProperty.call(hide_ui_View.viewClasses.h,componentName)) {
		console.log("hide/ui/View.hx:134:","[View] ⚠️ Already registered: " + componentName);
		return;
	}
	hide_ui_View.viewClasses.h[componentName] = { cls : cls, options : options != null ? options : { position : "Center"}};
	console.log("hide/ui/View.hx:141:","[View] ✅ Registered: " + componentName);
};
hide_ui_View.glFactory = function(componentName) {
	return function(container,state) {
		var config = hide_ui_View.viewClasses.h[componentName];
		if(config == null) {
			console.log("hide/ui/View.hx:150:","[View] ❌ Unknown component: " + componentName);
			return null;
		}
		var instance = Type.createInstance(config.cls,[container,state]);
		return instance;
	};
};
hide_ui_View.prototype = {
	init: function() {
	}
	,activate: function() {
		this.isActive = true;
		console.log("hide/ui/View.hx:71:","[View] ✅ Activated: " + this.viewClass);
		this.onActivate();
	}
	,onActivate: function() {
	}
	,destroy: function() {
		console.log("hide/ui/View.hx:110:","[View] 🗑 Destroyed: " + this.viewClass);
		this.element.innerHTML = "";
	}
};
var hide_view_CdbTable = function(container,state) {
	hide_ui_View.call(this,container,state,"hide.view.CdbTable");
};
hide_view_CdbTable.__name__ = true;
hide_view_CdbTable.__super__ = hide_ui_View;
hide_view_CdbTable.prototype = $extend(hide_ui_View.prototype,{
	init: function() {
		console.log("hide/view/CdbTable.hx:30:","[CdbTable] 🎨 init()");
		this.buildUI();
		this.setupEvents();
		var tmp = this.state;
		if((tmp != null ? tmp.data : null) != null) {
			this.renderData(this.state.data);
		}
	}
	,buildUI: function() {
		this.element.innerHTML = "\r\n        <div class=\"view-header\">\r\n            <span class=\"view-title\">🗄 Database</span>\r\n            <button class=\"btn btn-sm\" id=\"btn-refresh\">⟳</button>\r\n        </div>\r\n        <div class=\"view-body\">\r\n            <div class=\"empty-state\" id=\"empty\">\r\n                <p>📭 No data</p>\r\n                <button class=\"btn\" id=\"btn-load\">Load Sample</button>\r\n            </div>\r\n            <table class=\"data-table\" id=\"table\" style=\"display:none\">\r\n                <thead><tr><th>ID</th><th>Name</th><th>Type</th></tr></thead>\r\n                <tbody id=\"tbody\"></tbody>\r\n            </table>\r\n        </div>\r\n        <div class=\"view-footer\">\r\n            <span id=\"status\">Ready</span>\r\n        </div>\r\n        ";
		this.tbody = this.element.querySelector("#tbody");
		this.statusEl = this.element.querySelector("#status");
		this.element.querySelector(".view-header").style.cssText = "padding:8px 12px;background:#f5f5f5;border-bottom:1px solid #ddd;display:flex;justify-content:space-between;";
		this.element.querySelector(".view-body").style.cssText = "flex:1;overflow:auto;padding:12px;";
		this.element.querySelector(".data-table").style.cssText = "width:100%;border-collapse:collapse;font-size:12px;";
		this.element.querySelector(".data-table th").style.cssText = "background:#f0f0f0;text-align:left;padding:6px 8px;border-bottom:2px solid #ddd;";
		this.element.querySelector(".data-table td").style.cssText = "padding:6px 8px;border-bottom:1px solid #eee;";
	}
	,setupEvents: function() {
		var _gthis = this;
		var loadBtn = this.element.querySelector("#btn-load");
		if(loadBtn != null) {
			loadBtn.addEventListener("click",function(_) {
				_gthis.loadSampleData();
			});
		}
		var refreshBtn = this.element.querySelector("#btn-refresh");
		if(refreshBtn != null) {
			refreshBtn.addEventListener("click",function(_) {
				_gthis.setStatus("Refreshing...");
				haxe_Timer.delay(function() {
					_gthis.setStatus("Ready");
				},300);
			});
		}
		this.container.on("open",function() {
			_gthis.activate();
		});
		this.container.on("destroy",function() {
			_gthis.destroy();
		});
	}
	,loadSampleData: function() {
		var data = [{ id : 1, name : "Players", type : "Table"},{ id : 2, name : "Items", type : "Table"},{ id : 3, name : "Quests", type : "Table"}];
		this.renderData(data);
		this.setStatus("Loaded ${data.length} items");
	}
	,renderData: function(rows) {
		var empty = this.element.querySelector("#empty");
		var table = this.element.querySelector("#table");
		if(empty != null) {
			empty.style.display = "none";
		}
		if(table != null) {
			table.style.display = "table";
		}
		if(this.tbody != null) {
			this.tbody.innerHTML = "";
			var _g = 0;
			while(_g < rows.length) {
				var row = rows[_g];
				++_g;
				var tr = window.document.createElement("tr");
				tr.innerHTML = "<td>" + Std.string(row.id) + "</td><td>" + Std.string(row.name) + "</td><td>" + Std.string(row.type) + "</td>";
				this.tbody.appendChild(tr);
			}
		}
	}
	,setStatus: function(text) {
		if(this.statusEl != null) {
			this.statusEl.textContent = text;
		}
	}
	,onActivate: function() {
		console.log("hide/view/CdbTable.hx:133:","[CdbTable] 👁 Panel activated");
	}
	,destroy: function() {
		console.log("hide/view/CdbTable.hx:137:","[CdbTable] 🧹 Cleanup");
		hide_ui_View.prototype.destroy.call(this);
	}
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
String.__name__ = true;
Array.__name__ = true;
hide_ui_View.viewClasses = new haxe_ds_StringMap();
hide_ui_View.register("hide.view.CdbTable",hide_view_CdbTable,{ position : "Center", id : "cdbTable"});
js_Boot.__toStr = ({ }).toString;
hide_core_IdeConfig.appPath = "";
hide_core_IdeConfig.isElectron = false;
hide_core_IdeConfig.debugMode = false;
hide_core_Ide.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=app.js.map