// Generated by Haxe 4.3.0
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var electron_renderer_IpcRenderer = require("electron").ipcRenderer;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
});
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var hide_core_Ide = function() {
	this.isInitialized = false;
	hide_core_Ide.inst = this;
	hide_core_IdeConfig.init();
	this.backend = hide_core_Ide.createBackend();
	this.backend.init();
	hide_core_IdeConfig.appPath = this.backend.getAppPath();
};
hide_core_Ide.__name__ = true;
hide_core_Ide.createBackend = function() {
	return new hide_electron_ElectronBackend();
};
hide_core_Ide.main = function() {
	window.onload = function() {
		console.log("hide/core/Ide.hx:286:","🌐 Renderer process starting...");
		window.document.getElementById("system-version").textContent = "🌐 Renderer process starting...";
		var app = new hide_core_Ide();
		app.init();
	};
};
hide_core_Ide.prototype = {
	open: function(componentName,state,position) {
		console.log("hide/core/Ide.hx:55:","[Ide] 🪟 Opening component: " + componentName);
		var url = "app.html?subView=" + componentName;
		if(state != null) {
			var stateJson = JSON.stringify(state);
			url += "&state=" + js_node_Url.format(stateJson);
		}
		if(position != null) {
			url += "&pos=" + position;
		}
		this.backend.openWindow(url,{ title : componentName.split(".").pop(), width : 800, height : 600, id : componentName},componentName);
		console.log("hide/core/Ide.hx:80:","[Ide] ✅ Window request sent: " + url);
	}
	,getBackend: function() {
		return this.backend;
	}
	,init: function() {
		var _gthis = this;
		if(this.isInitialized) {
			return;
		}
		console.log("hide/core/Ide.hx:112:","🚀 Hide IDE initializing...");
		this.windowManager = new hide_modules_WindowManager(this);
		this.menuSystem = new hide_modules_MenuSystem(this);
		this.menuSystem.loadFromXml();
		this.menuSystem.registerCommand("exit",function() {
			console.log("hide/core/Ide.hx:123:","🚪 Exit");
			_gthis.getBackend().quit();
		});
		this.menuSystem.registerCommand("open",function() {
			console.log("hide/core/Ide.hx:128:","📂 Open project");
		});
		this.menuSystem.registerCommand("clear",function() {
			console.log("hide/core/Ide.hx:133:","🗑 Clear recents");
		});
		this.menuSystem.registerCommand("clear-local",function() {
			console.log("hide/core/Ide.hx:138:","🧹 Clear local profile");
			window.localStorage.clear();
			_gthis.getBackend().clearCache();
			_gthis.getBackend().reload();
		});
		this.menuSystem.registerCommand("build-files",function() {
			console.log("hide/core/Ide.hx:145:","🔨 Build files");
		});
		this.menuSystem.registerCommand("debug",function() {
			console.log("hide/core/Ide.hx:151:","🐛 DevTools");
			_gthis.getBackend().showDevTools();
		});
		this.menuSystem.registerCommand("hide.view.FileBrowser",function() {
			_gthis.open("hide.view.FileBrowser",{ });
		});
		this.menuSystem.registerCommand("hide.view.DomkitStudio",function() {
			_gthis.open("hide.view.DomkitStudio",{ });
		});
		this.menuSystem.registerCommand("hide.view.About",function() {
			_gthis.open("hide.view.About",{ });
		});
		this.menuSystem.registerCommand("hide.view.Gym",function() {
			_gthis.open("hide.view.Gym",{ });
		});
		this.menuSystem.registerCommand("dbView",function() {
			_gthis.open("app.html",{ });
		});
		this.menuSystem.registerCommand("dbCustom",function() {
			console.log("hide/core/Ide.hx:176:","⚙️ DB Custom Types");
		});
		this.menuSystem.registerCommand("dbCompress",function() {
			console.log("hide/core/Ide.hx:179:","🗜 DB Compress toggle");
		});
		this.menuSystem.registerCommand("dbExport",function() {
			console.log("hide/core/Ide.hx:182:","📤 DB Export");
		});
		this.menuSystem.registerCommand("dbImport",function() {
			console.log("hide/core/Ide.hx:185:","📥 DB Import");
		});
		this.menuSystem.registerCommand("dbProofread",function() {
			console.log("hide/core/Ide.hx:188:","👁 DB Proofread toggle");
		});
		this.menuSystem.registerCommand("save",function() {
			console.log("hide/core/Ide.hx:193:","💾 Save layout");
		});
		this.menuSystem.registerCommand("saveas",function() {
			console.log("hide/core/Ide.hx:196:","💾 Save As...");
		});
		this.menuSystem.registerCommand("autosave",function() {
			console.log("hide/core/Ide.hx:199:","🔄 Autosave toggle");
		});
		this.menuSystem.registerCommand("user-settings",function() {
			console.log("hide/core/Ide.hx:204:","⚙️ User settings");
		});
		this.menuSystem.registerCommand("project-settings",function() {
			console.log("hide/core/Ide.hx:207:","⚙️ Project settings");
		});
		this.registerGoldenLayoutComponents();
		this.isInitialized = true;
		console.log("hide/core/Ide.hx:230:","✅ Hide IDE ready (stub mode).");
		window.document.getElementById("system-version").textContent = "✅ Hide IDE ready (stub mode).";
	}
	,registerGoldenLayoutComponents: function() {
		var wm = this.windowManager;
		if(wm == null || wm.goldenLayout == null) {
			console.log("hide/core/Ide.hx:244:","[Ide] ⏳ GoldenLayout not ready yet (will register later)");
			return;
		}
		console.log("hide/core/Ide.hx:248:","[Ide] ✅ GoldenLayout connected, registering components...");
		wm.goldenLayout.registerComponent("hide.view.CdbTable",function(container,state) {
			console.log("hide/core/Ide.hx:253:","[GL] Creating CdbTable panel");
			container.getElement().html("<div class=\"cdb-table\">CdbTable placeholder</div>");
		});
		wm.goldenLayout.registerComponent("hide.view.FileBrowser",function(container,state) {
			console.log("hide/core/Ide.hx:258:","[GL] Creating FileBrowser panel");
			container.getElement().html("<div class=\"file-browser\">FileBrowser placeholder</div>");
		});
		wm.goldenLayout.registerComponent("hide.view.DomkitStudio",function(container,state) {
			console.log("hide/core/Ide.hx:263:","[GL] Creating DomkitStudio panel");
			container.getElement().html("<div>DomkitStudio placeholder</div>");
		});
		wm.goldenLayout.registerComponent("hide.view.About",function(container,state) {
			console.log("hide/core/Ide.hx:268:","[GL] Creating About panel");
			container.getElement().html("<div>About Hide IDE</div>");
		});
		wm.goldenLayout.registerComponent("hide.view.Gym",function(container,state) {
			console.log("hide/core/Ide.hx:273:","[GL] Creating Gym panel");
			container.getElement().html("<div>Editor Gym placeholder</div>");
		});
	}
};
var hide_core_IdeConfig = function() { };
hide_core_IdeConfig.__name__ = true;
hide_core_IdeConfig.init = function() {
	hide_core_IdeConfig.isElectron = true;
	hide_core_IdeConfig.debugMode = true;
};
var hide_electron_ElectronBackend = function() {
	this.menuClickHandler = null;
};
hide_electron_ElectronBackend.__name__ = true;
hide_electron_ElectronBackend.prototype = {
	init: function() {
		var _gthis = this;
		console.log("hide/electron/ElectronBackend.hx:14:","[ElectronBackend] init()");
		electron_renderer_IpcRenderer.on("menu:click",function(event,data) {
			console.log("hide/electron/ElectronBackend.hx:18:","[ElectronBackend] 📥 menu:click received");
			if(_gthis.menuClickHandler != null && data != null && data.id != null) {
				_gthis.menuClickHandler(data.id);
			}
		});
		electron_renderer_IpcRenderer.on("app:clearCache:done",function(event,_) {
			console.log("hide/electron/ElectronBackend.hx:26:","[ElectronBackend] 🧹 Cache cleared");
			window.localStorage.clear();
		});
	}
	,openWindow: function(url,options,id) {
		console.log("hide/electron/ElectronBackend.hx:35:","[ElectronBackend] openWindow: " + url);
		if(url.indexOf("?subView=") != -1) {
			console.log("hide/electron/ElectronBackend.hx:40:","[ElectronBackend] 🪟 Sub-view request, dispatching locally");
			var params_h = Object.create(null);
			var query = url.split("?")[1];
			if(query != null) {
				var _g = 0;
				var _g1 = query.split("&");
				while(_g < _g1.length) {
					var pair = _g1[_g];
					++_g;
					var parts = pair.split("=");
					if(parts.length == 2) {
						var decoded = decodeURIComponent(parts[1]);
						params_h[parts[0]] = decoded;
					}
				}
			}
			var jsWindow = window;
			if(Object.prototype.hasOwnProperty.call(params_h,"subView") && jsWindow.hide != null && jsWindow.hide.Ide != null && jsWindow.hide.Ide.inst != null) {
				var componentName = params_h["subView"];
				var state = null;
				if(Object.prototype.hasOwnProperty.call(params_h,"state")) {
					try {
						var stateRaw = params_h["state"];
						var stateDecoded = decodeURIComponent(stateRaw);
						state = JSON.parse(stateDecoded);
					} catch( _g ) {
						var e = haxe_Exception.caught(_g).unwrap();
						console.log("hide/electron/ElectronBackend.hx:75:","[ElectronBackend] ⚠️ Failed to parse state: " + Std.string(e));
					}
				}
				var position = params_h["pos"];
				jsWindow.hide.Ide.inst.open(componentName,state,position);
			} else {
				console.log("hide/electron/ElectronBackend.hx:84:","[ElectronBackend] ⚠️ Ide not ready yet for subView");
			}
			return;
		}
		electron_renderer_IpcRenderer.send("window:open",{ url : url, options : options, id : id});
	}
	,createMenu: function(menuData) {
		var serialized = JSON.stringify(menuData);
		console.log("hide/electron/ElectronBackend.hx:101:","[ElectronBackend] 📤 Sending menu JSON: " + serialized);
		electron_renderer_IpcRenderer.send("menu:build",menuData);
	}
	,onMenuClick: function(handler) {
		console.log("hide/electron/ElectronBackend.hx:106:","[ElectronBackend] 📡 onMenuClick registered");
		this.menuClickHandler = handler;
	}
	,clearCache: function() {
		electron_renderer_IpcRenderer.send("app:clearCache");
	}
	,reload: function() {
		electron_renderer_IpcRenderer.send("app:reload");
	}
	,quit: function() {
		electron_renderer_IpcRenderer.send("app:quit");
	}
	,getAppPath: function() {
		return "./";
	}
	,showDevTools: function() {
		require('electron').remote.getCurrentWindow().webContents.openDevTools();
	}
};
var hide_modules_MenuSystem = function(ide) {
	this.ide = ide;
	this.commands = new haxe_ds_StringMap();
};
hide_modules_MenuSystem.__name__ = true;
hide_modules_MenuSystem.prototype = {
	loadFromXml: function() {
		var _gthis = this;
		var buildMenu = function() {
			var xmlEl = window.document.getElementById("mainmenu");
			if(xmlEl == null) {
				console.log("hide/modules/MenuSystem.hx:29:","[MenuSystem] ⚠️ mainmenu XML not found!");
				return;
			}
			var menuData = [];
			var _g = 0;
			var _g1 = xmlEl.children.length;
			while(_g < _g1) {
				var i = _g++;
				var item = _gthis.parseMenuItem(xmlEl.children[i]);
				if(item != null) {
					menuData.push(item);
				}
			}
			console.log("hide/modules/MenuSystem.hx:39:","[MenuSystem] 📤 Sending menu to Main: " + JSON.stringify(menuData));
			_gthis.ide.getBackend().createMenu(menuData);
			_gthis.ide.getBackend().onMenuClick($bind(_gthis,_gthis.handleCommand));
		};
		if(window.document.readyState == "complete" || window.document.readyState == "interactive") {
			buildMenu();
		} else {
			window.document.addEventListener("DOMContentLoaded",function(_) {
				buildMenu();
			});
		}
	}
	,registerCommand: function(id,handler) {
		this.commands.h[id] = handler;
		console.log("hide/modules/MenuSystem.hx:57:","[MenuSystem] ✅ Registered: " + id);
	}
	,handleCommand: function(id) {
		console.log("hide/modules/MenuSystem.hx:64:","[MenuSystem] 🔍 Command requested: '" + id + "'");
		if(Object.prototype.hasOwnProperty.call(this.commands.h,id)) {
			console.log("hide/modules/MenuSystem.hx:67:","[MenuSystem] ▶ Executing: " + id);
			this.commands.h[id]();
		} else {
			console.log("hide/modules/MenuSystem.hx:70:","[MenuSystem] ❌ Unknown command: '" + id + "'");
		}
	}
	,parseMenuItem: function(el) {
		var tag = el.tagName.toLowerCase();
		if(tag == "xml" || tag == "content") {
			return null;
		}
		if(tag == "separator") {
			return { label : "", type : "separator"};
		}
		if(tag == "div") {
			return { label : el.getAttribute("label") != null ? el.getAttribute("label") : "Section", enabled : false, submenu : []};
		}
		var label = el.getAttribute("label");
		if(label == null) {
			return null;
		}
		var cmd = null;
		if(el.getAttribute("class") != null) {
			cmd = el.getAttribute("class");
		} else if(el.getAttribute("onclick") != null) {
			cmd = el.getAttribute("onclick");
		} else if(el.getAttribute("id") != null) {
			cmd = el.getAttribute("id");
		} else if(el.getAttribute("command") != null) {
			cmd = el.getAttribute("command");
		}
		if(cmd != null) {
			cmd = StringTools.replace(cmd,"()","");
		}
		var type = el.getAttribute("type");
		var disabled = el.getAttribute("disabled") != null;
		var item = { label : label, id : cmd, type : type, enabled : !disabled};
		if(el.children != null && el.children.length > 0) {
			var submenu = [];
			var _g = 0;
			var _g1 = el.children.length;
			while(_g < _g1) {
				var i = _g++;
				var child = this.parseMenuItem(el.children[i]);
				if(child != null) {
					submenu.push(child);
				}
			}
			if(submenu.length > 0) {
				item.submenu = submenu;
			}
		}
		console.log("hide/modules/MenuSystem.hx:143:","[MenuSystem] Parsed: '" + label + "' → id='" + item.id + "'");
		return item;
	}
};
var hide_modules_WindowManager = function(ide) {
	this.goldenLayout = null;
	this.ide = ide;
};
hide_modules_WindowManager.__name__ = true;
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_node_Url = require("url");
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
hide_core_IdeConfig.appPath = "";
hide_core_IdeConfig.isElectron = false;
hide_core_IdeConfig.debugMode = false;
hide_core_Ide.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=app.js.map