// Generated by Haxe 4.3.6
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var AutoWindow = function() { };
AutoWindow.__name__ = true;
AutoWindow.start = function(overrides) {
	AutoWindow.cfg = AutoWindow.loadPackageConfig();
	console.log("AutoWindow.hx:44:",AutoWindow.cfg);
	AutoWindow.applyDefaults();
	console.log("AutoWindow.hx:47:",AutoWindow.cfg);
	if(overrides != null) {
		if(overrides.width != null) {
			AutoWindow.cfg.width = overrides.width;
		}
		if(overrides.height != null) {
			AutoWindow.cfg.height = overrides.height;
		}
		if(overrides.minWidth != null) {
			AutoWindow.cfg.minWidth = overrides.minWidth;
		}
		if(overrides.minHeight != null) {
			AutoWindow.cfg.minHeight = overrides.minHeight;
		}
		if(overrides.title != null) {
			AutoWindow.cfg.title = overrides.title;
		}
		if(overrides.icon != null) {
			AutoWindow.cfg.icon = overrides.icon;
		}
		if(overrides.show != null) {
			AutoWindow.cfg.show = overrides.show;
		}
		if(overrides.frame != null) {
			AutoWindow.cfg.frame = overrides.frame;
		}
		if(overrides.x != null) {
			AutoWindow.cfg.x = overrides.x;
		}
		if(overrides.y != null) {
			AutoWindow.cfg.y = overrides.y;
		}
		if(overrides.url != null) {
			AutoWindow.cfg.url = overrides.url;
		}
		if(overrides.onReady != null) {
			AutoWindow.cfg.onReady = overrides.onReady;
		}
		if(overrides.onClose != null) {
			AutoWindow.cfg.onClose = overrides.onClose;
		}
	}
	console.log("AutoWindow.hx:64:",AutoWindow.cfg);
	electron_main_App.whenReady().then(function(_) {
		AutoWindow.createWindow();
		AutoWindow.setupLifecycle();
		AutoWindow.setupIpc();
		if(AutoWindow.cfg.onReady != null) {
			AutoWindow.cfg.onReady();
		}
	});
};
AutoWindow.loadPackageConfig = function() {
	try {
		var pkgPath = js_node_Path.join(__dirname,"package.json");
		var pkg = JSON.parse(js_node_Fs.readFileSync(pkgPath,{ encoding : "utf8"}));
		var win = pkg.window != null ? pkg.window : { };
		return { width : win.width, height : win.height, minWidth : win.min_width, minHeight : win.min_height, title : win.title, icon : win.icon, show : win.show, frame : win.frame, x : win.x, y : win.y, url : win.url};
	} catch( _g ) {
		return { };
	}
};
AutoWindow.applyDefaults = function() {
	if(AutoWindow.cfg.width == null) {
		AutoWindow.cfg.width = 1200;
	}
	if(AutoWindow.cfg.height == null) {
		AutoWindow.cfg.height = 800;
	}
	if(AutoWindow.cfg.title == null) {
		AutoWindow.cfg.title = "HIDE IDE";
	}
	if(AutoWindow.cfg.url == null) {
		AutoWindow.cfg.url = "app-electron.html";
	}
	if(AutoWindow.cfg.show == null) {
		AutoWindow.cfg.show = true;
	}
	if(AutoWindow.cfg.frame == null) {
		AutoWindow.cfg.frame = false;
	}
};
AutoWindow.createWindow = function() {
	var opts = { width : AutoWindow.cfg.width, height : AutoWindow.cfg.height, minWidth : AutoWindow.cfg.minWidth, minHeight : AutoWindow.cfg.minHeight, title : AutoWindow.cfg.title, show : false, frame : false, titleBarStyle : "hidden", webPreferences : { nodeIntegration : true, contextIsolation : false, enableRemoteModule : true}};
	if(AutoWindow.cfg.icon != null) {
		opts.icon = js_node_Path.join(__dirname,AutoWindow.cfg.icon);
	}
	if(AutoWindow.cfg.x != null && AutoWindow.cfg.y != null) {
		opts.x = AutoWindow.cfg.x;
		opts.y = AutoWindow.cfg.y;
	}
	AutoWindow.window = new electron_main_BrowserWindow(opts);
	AutoWindow.window.loadFile(AutoWindow.cfg.url);
	AutoWindow.window.on("ready-to-show",function() {
		if(AutoWindow.cfg.show) {
			AutoWindow.window.show();
		}
		AutoWindow.window.focus();
	});
	AutoWindow.window.on("close",function(_) {
		if(AutoWindow.cfg.onClose != null) {
			AutoWindow.cfg.onClose();
		}
	});
};
AutoWindow.setupLifecycle = function() {
	electron_main_App.on("window-all-closed",function() {
		if(Sys.systemName() != "Mac") {
			electron_main_App.quit();
		}
	});
	electron_main_App.on("activate",function() {
		if(electron_main_BrowserWindow.getAllWindows().length == 0) {
			AutoWindow.createWindow();
		}
	});
};
AutoWindow.ensureDirectoryExists = function(dir) {
	if(dir == null || dir == "") {
		return;
	}
	if(js_node_Fs.existsSync(dir)) {
		return;
	}
	AutoWindow.ensureDirectoryExists(js_node_Path.dirname(dir));
	js_node_Fs.mkdirSync(dir);
};
AutoWindow.setupIpc = function() {
	electron_main_IpcMain.handle("asset:getList",function(event,data) {
		var pipeline = src_main_services_ServiceLocator.get().assetPipeline;
		if(pipeline == null) {
			return { success : false, error : "AssetPipeline not initialized"};
		}
		try {
			var folder = data.folder != null ? data.folder : null;
			var items = pipeline.getAssetsList(folder);
			return { success : true, data : items};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			return { success : false, error : Std.string(e)};
		}
	});
	electron_main_IpcMain.handle("project:readDir",function(event,data) {
		var fs = js_node_Fs;
		var pathLib = js_node_Path;
		var pipeline = src_main_services_ServiceLocator.get().assetPipeline;
		if(pipeline == null) {
			return { success : false, error : "No project loaded"};
		}
		var root = pipeline.getProjectRoot();
		var targetDir = data.path != null ? data.path : root;
		console.log("AutoWindow.hx:322:","🔍 [Backend] readDir requested for: " + targetDir);
		console.log("AutoWindow.hx:323:","   Project Root: " + root);
		if(!StringTools.startsWith(targetDir,root)) {
			console.log("AutoWindow.hx:327:","❌ [Backend] Access denied: " + targetDir + " is outside " + root);
			return { success : false, error : "Access denied: path outside project root"};
		}
		try {
			if(!fs.existsSync(targetDir)) {
				console.log("AutoWindow.hx:333:","⚠️ [Backend] Directory not found: " + targetDir);
				return { success : true, data : []};
			}
			var entries = fs.readdirSync(targetDir);
			var result = [];
			var _g = 0;
			while(_g < entries.length) {
				var entry = entries[_g];
				++_g;
				if(StringTools.startsWith(entry,".") || entry == "node_modules") {
					continue;
				}
				var fullPath = pathLib.join(targetDir,entry);
				var stat = fs.statSync(fullPath);
				var relPath = pathLib.relative(root,fullPath).split("\\").join("/");
				result.push({ name : entry, path : fullPath, relativePath : relPath, isDirectory : stat.isDirectory(), extension : stat.isFile() ? entry.split(".").pop().toLowerCase() : null});
			}
			result.sort(function(a,b) {
				if(a.isDirectory && !b.isDirectory) {
					return -1;
				}
				if(!a.isDirectory && b.isDirectory) {
					return 1;
				}
				if(a.name.toLowerCase() < b.name.toLowerCase()) {
					return -1;
				} else {
					return 1;
				}
			});
			console.log("AutoWindow.hx:363:","✅ [Backend] Listed " + result.length + " items in: " + targetDir);
			return { success : true, data : result};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			console.log("AutoWindow.hx:366:","❌ [Backend] Error reading dir: " + Std.string(e));
			return { success : false, error : Std.string(e)};
		}
	});
	electron_main_IpcMain.handle("asset:init",function(event,data) {
		var pipeline = src_main_services_ServiceLocator.get().assetPipeline;
		if(pipeline == null) {
			return { success : false, error : "AssetPipeline not initialized in ServiceLocator"};
		}
		try {
			pipeline.setProjectRoot(data.projectRoot);
			console.log("AutoWindow.hx:382:","✅ [Main] Asset Pipeline initialized for: " + Std.string(data.projectRoot));
			console.log("AutoWindow.hx:383:","   Assets folder: " + Std.string(data.assetsFolder));
			console.log("AutoWindow.hx:384:","   Build folder: " + Std.string(data.buildFolder));
			return { success : true, data : { assetsPath : pipeline.getAssetsPath(), supportedExtensions : pipeline.getSupportedExtensions()}};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			console.log("AutoWindow.hx:394:","❌ [Main] Failed to init Asset Pipeline: " + Std.string(e));
			return { success : false, error : Std.string(e)};
		}
	});
	electron_main_IpcMain.handle("asset:getMeta",function(event,guid) {
		var pipeline = src_main_services_ServiceLocator.get().assetPipeline;
		if(pipeline == null) {
			return { success : false, error : "Pipeline not ready"};
		}
		var meta = pipeline.getMeta(guid);
		if(meta != null) {
			return { success : true, data : meta};
		} else {
			return { success : false, error : "Meta not found for GUID: " + guid};
		}
	});
	electron_main_IpcMain.handle("asset:import",function(event,paths) {
		var pipeline = src_main_services_ServiceLocator.get().assetPipeline;
		if(pipeline == null) {
			return { success : false, error : "Pipeline not ready"};
		}
		return new Promise((resolve) => {
                pipeline.importAssets(paths).then(function(results) {
                    resolve({ success: true, data: results });
                }).catch(function(err) {
                    resolve({ success: false, error: err.message || String(err) });
                });
            });
	});
	electron_main_IpcMain.on("app:quit",function(event) {
		electron_main_App.quit();
	});
	electron_main_IpcMain.on("app:reload",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.reload();
		}
	});
	electron_main_IpcMain.on("fs:exists",function(event,filePath) {
		try {
			event.returnValue = js_node_Fs.existsSync(filePath);
		} catch( _g ) {
			event.returnValue = false;
		}
	});
	electron_main_IpcMain.on("fs:readText",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var content = js_node_Fs.readFileSync(filePath,{ encoding : "utf-8"});
				event.returnValue = { content : content};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:readBinary",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var buffer = js_node_Fs.readFileSync(filePath);
				var base64 = buffer.toString("base64");
				event.returnValue = { data : base64};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:writeText",function(event,data) {
		try {
			var dir = js_node_Path.dirname(data.path);
			if(!js_node_Fs.existsSync(dir)) {
				AutoWindow.ensureDirectoryExists(dir);
			}
			js_node_Fs.writeFileSync(data.path,data.content,{ encoding : "utf-8"});
			event.returnValue = { };
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:listFiles",function(event,data) {
		try {
			var files = [];
			var scan = null;
			scan = function(dir) {
				var entries = js_node_Fs.readdirSync(dir);
				var _g = 0;
				while(_g < entries.length) {
					var entry = entries[_g];
					++_g;
					var fullPath = js_node_Path.join(dir,entry);
					var stat = js_node_Fs.statSync(fullPath);
					if(stat.isDirectory() && data.recursive) {
						scan(fullPath);
					} else if(stat.isFile()) {
						files.push(fullPath);
					}
				}
			};
			if(js_node_Fs.existsSync(data.path)) {
				scan(data.path);
			}
			event.returnValue = { files : files};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("app:getAppDataPath",function(event) {
		event.returnValue = electron_main_App.getPath("userData");
	});
	electron_main_IpcMain.handle("dialog:showOpen",function(event,options) {
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showSave",function(event,options) {
		return electron_main_Dialog.showSaveDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showDirectory",function(event,options) {
		options.properties = ["openDirectory","createDirectory"];
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.on("window:setTitle",function(event,title) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setTitle(title);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:enterFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(true);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:maximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.maximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:minimize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.minimize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:unmaximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.unmaximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:leaveFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(false);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("menu:build",function(event,menuData) {
		console.log("AutoWindow.hx:564:","[AutoWindow] 📥 Received menu data");
	});
	electron_main_IpcMain.on("window:open",function(event,data) {
		var url = data.url;
		if(url.indexOf("?subView=") != -1) {
			console.log("AutoWindow.hx:605:","[AutoWindow] ⚠️ Sub-view request: " + url);
			event.sender.send("window:open:subview",{ url : url});
			return;
		}
		var opts = { width : data.options.width != null ? data.options.width : 800, height : data.options.height != null ? data.options.height : 600, title : data.options.title != null ? data.options.title : "Hide", parent : AutoWindow.window, webPreferences : { nodeIntegration : true, contextIsolation : false}};
		var child = new electron_main_BrowserWindow(opts);
		child.loadFile(url);
	});
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
var ElectronMain = function() { };
ElectronMain.__name__ = true;
ElectronMain.main = function() {
	src_main_services_ServiceLocator.init();
	AutoWindow.start({ onReady : ElectronMain.startup});
};
ElectronMain.startup = function() {
	console.log("ElectronMain.hx:23:","🚀 ElectronMain: Startup complete");
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.startsWith = function(s,start) {
	if(s.length >= start.length) {
		return s.lastIndexOf(start,0) == 0;
	} else {
		return false;
	}
};
StringTools.endsWith = function(s,end) {
	var elen = end.length;
	var slen = s.length;
	if(slen >= elen) {
		return s.indexOf(end,slen - elen) == slen - elen;
	} else {
		return false;
	}
};
var Sys = function() { };
Sys.__name__ = true;
Sys.systemName = function() {
	var _g = process.platform;
	switch(_g) {
	case "darwin":
		return "Mac";
	case "freebsd":
		return "BSD";
	case "linux":
		return "Linux";
	case "win32":
		return "Windows";
	default:
		var other = _g;
		return other;
	}
};
var chokidar_Chokidar = require("chokidar");
var electron_main_App = require("electron").app;
var electron_main_BrowserWindow = require("electron").BrowserWindow;
var electron_main_Dialog = require("electron").dialog;
var electron_main_IpcMain = require("electron").ipcMain;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
});
var haxe_ds_Either = $hxEnums["haxe.ds.Either"] = { __ename__:true,__constructs__:null
	,Left: ($_=function(v) { return {_hx_index:0,v:v,__enum__:"haxe.ds.Either",toString:$estr}; },$_._hx_name="Left",$_.__params__ = ["v"],$_)
	,Right: ($_=function(v) { return {_hx_index:1,v:v,__enum__:"haxe.ds.Either",toString:$estr}; },$_._hx_name="Right",$_.__params__ = ["v"],$_)
};
haxe_ds_Either.__constructs__ = [haxe_ds_Either.Left,haxe_ds_Either.Right];
var haxe_ds_StringMap = function() {
	this.h = Object.create(null);
};
haxe_ds_StringMap.__name__ = true;
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_node_Fs = require("fs");
var js_node_Path = require("path");
var src_main_assets_AssetPipelineService = function(registry) {
	this.registry = registry;
	this.projectRoot = "";
	this.assetsPath = "";
};
src_main_assets_AssetPipelineService.__name__ = true;
src_main_assets_AssetPipelineService.prototype = {
	setProjectRoot: function(root) {
		this.projectRoot = root;
		var normalizedRoot = root.split("\\").join("/");
		this.assetsPath = js_node_Path.join(normalizedRoot,"Assets");
		this.stopWatching();
		this.startWatching();
		console.log("src/main/assets/AssetPipelineService.hx:46:","📂 [AssetPipeline] Project root set to: " + normalizedRoot);
		console.log("src/main/assets/AssetPipelineService.hx:47:","   Watching: " + this.assetsPath);
	}
	,getProjectRoot: function() {
		return this.projectRoot;
	}
	,getAssetsPath: function() {
		return this.assetsPath;
	}
	,getSupportedExtensions: function() {
		return this.registry.getAllSupportedExtensions();
	}
	,getMeta: function(guid) {
		if(this.projectRoot == "") {
			return null;
		}
		return this.findMetaByGuid(this.assetsPath,guid);
	}
	,startWatching: function() {
		var _gthis = this;
		if(this.assetsPath == "" || !js_node_Fs.existsSync(this.assetsPath)) {
			console.log("src/main/assets/AssetPipelineService.hx:101:","⚠️ [AssetPipeline] Assets folder does not exist yet: " + this.assetsPath);
			try {
				require('fs').mkdirSync(this.assetsPath, { recursive: true });
				console.log("src/main/assets/AssetPipelineService.hx:104:","✅ [AssetPipeline] Created missing Assets folder");
			} catch( _g ) {
				var e = haxe_Exception.caught(_g).unwrap();
				console.log("src/main/assets/AssetPipelineService.hx:106:","❌ [AssetPipeline] Failed to create Assets folder: " + Std.string(e));
				return;
			}
		}
		var awfOptions = { stabilityThreshold : 1000, pollInterval : 500};
		console.log("src/main/assets/AssetPipelineService.hx:115:","👀 [AssetPipeline] Starting Chokidar watcher on: " + this.assetsPath);
		var options = { ignored : [new EReg("(\\^|[/\\\\])\\..",""),"**/*.meta"], persistent : true, awaitWriteFinish : haxe_ds_Either.Right(awfOptions), ignoreInitial : false, usePolling : true};
		this.watcher = chokidar_Chokidar.watch(this.assetsPath + "/**/*",options);
		this.watcher.on("add",function(path) {
			console.log("src/main/assets/AssetPipelineService.hx:131:","📥 [Chokidar] File ADDED: " + path);
			_gthis.onFileAdded(path);
		}).on("change",function(path) {
			console.log("src/main/assets/AssetPipelineService.hx:135:","🔄 [Chokidar] File CHANGED: " + path);
			_gthis.onFileChanged(path);
		}).on("unlink",function(path) {
			console.log("src/main/assets/AssetPipelineService.hx:139:","🗑️ [Chokidar] File DELETED: " + path);
			_gthis.onFileDeleted(path);
		}).on("error",function(error) {
			console.log("src/main/assets/AssetPipelineService.hx:143:","❌ [Chokidar] Error: " + Std.string(error));
		}).on("ready",function() {
			console.log("src/main/assets/AssetPipelineService.hx:146:","✅ [Chokidar] Initial scan complete. Watching for changes...");
			_gthis.onInitialScanComplete();
		});
		this.watcher.on("all",function(event,path) {
			console.log("src/main/assets/AssetPipelineService.hx:150:","🔍 [Chokidar ALL] Event: " + event + " | Path: " + Std.string(path));
		});
	}
	,stopWatching: function() {
		if(this.watcher != null) {
			this.watcher.close();
			this.watcher = null;
			console.log("src/main/assets/AssetPipelineService.hx:158:","🛑 [AssetPipeline] Watcher stopped");
		}
	}
	,getAssetsList: function(folder) {
		if(this.projectRoot == "") {
			return [];
		}
		var fs = js_node_Fs;
		var pathLib = js_node_Path;
		var targetDir = folder != null ? pathLib.join(this.assetsPath,folder) : this.assetsPath;
		if(!fs.existsSync(targetDir)) {
			console.log("src/main/assets/AssetPipelineService.hx:177:","⚠️ [AssetPipeline] Directory not found: " + targetDir);
			return [];
		}
		try {
			var entries = fs.readdirSync(targetDir);
			var result = [];
			var _g = 0;
			while(_g < entries.length) {
				var entry = entries[_g];
				++_g;
				if(StringTools.startsWith(entry,".") || StringTools.endsWith(entry,".meta")) {
					continue;
				}
				var fullPath = pathLib.join(targetDir,entry);
				var stat = fs.statSync(fullPath);
				var relPath = pathLib.relative(this.projectRoot,fullPath).split("\\").join("/");
				if(stat.isDirectory()) {
					result.push({ name : entry, path : fullPath, relativePath : relPath, isDirectory : true, guid : null, buildPath : null, type : "folder"});
				} else {
					var metaPath = fullPath + ".meta";
					var guid = null;
					var buildPath = null;
					if(fs.existsSync(metaPath)) {
						try {
							var metaContent = fs.readFileSync(metaPath,"utf-8");
							var meta = JSON.parse(metaContent);
							guid = meta.guid;
							buildPath = meta.buildPath;
						} catch( _g1 ) {
						}
					}
					var ext = entry.split(".").pop().toLowerCase();
					var assetType;
					switch(ext) {
					case "mp3":case "ogg":case "wav":
						assetType = "audio";
						break;
					case "jpeg":case "jpg":case "png":case "tga":case "webp":
						assetType = "image";
						break;
					default:
						assetType = "unknown";
					}
					result.push({ name : entry, path : fullPath, relativePath : relPath, isDirectory : false, guid : guid, buildPath : buildPath, type : assetType});
				}
			}
			return result;
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			console.log("src/main/assets/AssetPipelineService.hx:239:","❌ [AssetPipeline] Failed to list assets: " + Std.string(e));
			return [];
		}
	}
	,onInitialScanComplete: function() {
		console.log("src/main/assets/AssetPipelineService.hx:250:","✅ [AssetPipeline] Initial scan complete. System ready.");
	}
	,onFileAdded: function(path) {
		if(StringTools.endsWith(path,".meta")) {
			return;
		}
		console.log("src/main/assets/AssetPipelineService.hx:260:","📥 [AssetPipeline] New file detected: " + path);
		this.importSingleAsset(path);
	}
	,onFileChanged: function(path) {
		if(StringTools.endsWith(path,".meta")) {
			return;
		}
		console.log("src/main/assets/AssetPipelineService.hx:267:","🔄 [AssetPipeline] File changed: " + path);
		this.reimportAsset(path);
	}
	,onFileDeleted: function(path) {
		console.log("src/main/assets/AssetPipelineService.hx:272:","🗑️ [AssetPipeline] File deleted: " + path);
		this.cleanupBuildFiles(path);
	}
	,importSingleAsset: function(sourcePath) {
		var metaPath = sourcePath + ".meta";
		var fs = require('fs');
		var ext = js_node_Path.extname(sourcePath).toLowerCase();
		var relativeSource = js_node_Path.relative(this.projectRoot,sourcePath);
		var buildDir = js_node_Path.join(this.projectRoot,"Build",js_node_Path.dirname(relativeSource));
		var baseName = js_node_Path.basename(sourcePath,ext);
		var buildPath = js_node_Path.join(buildDir,baseName + ".webp");
		var meta = null;
		
            if (fs.existsSync(metaPath)) {
                meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
            } else {
                meta = {
                    guid: require('uuid').v4(),
                    type: 'texture',
                    sourcePath: relativeSource,
                    buildPath: buildPath.replace(/\\\\/g, '/'),
                    settings: {},
                    lastModified: fs.statSync(sourcePath).mtimeMs,
                    version: 1
                };
                
                if (!fs.existsSync(buildDir)) {
                    fs.mkdirSync(buildDir, { recursive: true });
                }
                
                fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2), 'utf-8');
                console.log(' [AssetPipeline] Created .meta for: ' + relativeSource);
            }
        ;
		var converter = this.registry.getConverter(sourcePath);
		if(converter == null) {
			console.log("src/main/assets/AssetPipelineService.hx:324:","⚠️ [AssetPipeline] No converter found for: " + sourcePath);
			return;
		}
		meta.type = "texture";
		var resultPromise = converter.convert(sourcePath,meta);
		
            resultPromise.then(function(res) {
                // Проверяем, что вернул конвертер
                var finalSource = res.sourcePath != null ? res.sourcePath : sourcePath;
                var finalBuild = res.buildPath != null ? res.buildPath : res; // Если вернул просто строку
                
                console.log('✅ [AssetPipeline] Converted: ' + finalSource + ' → ' + finalBuild);
                
                meta.lastModified = fs.statSync(sourcePath).mtimeMs;
                fs.writeFileSync(metaPath, JSON.stringify(meta, null, 2), 'utf-8');
            }).catch(function(err) {
                console.error('❌ [AssetPipeline] Conversion failed:', err);
            });
        ;
	}
	,reimportAsset: function(sourcePath) {
		this.importSingleAsset(sourcePath);
	}
	,cleanupBuildFiles: function(sourcePath) {
		
            const fs = require('fs');
            const path = require('path');
            
            const metaPath = sourcePath + '.meta';
            if (fs.existsSync(metaPath)) {
                const meta = JSON.parse(fs.readFileSync(metaPath, 'utf-8'));
                if (meta.buildPath && fs.existsSync(meta.buildPath)) {
                    fs.unlinkSync(meta.buildPath);
                    console.log('️ [AssetPipeline] Cleaned up build file: ' + meta.buildPath);
                }
                fs.unlinkSync(metaPath);
            }
        ;
	}
	,findMetaByGuid: function(dir,guid) {
		if(!js_node_Fs.existsSync(dir)) {
			return null;
		}
		var entries = js_node_Fs.readdirSync(dir);
		var _g = 0;
		while(_g < entries.length) {
			var entry = entries[_g];
			++_g;
			var fullPath = js_node_Path.join(dir,entry);
			var stat = js_node_Fs.statSync(fullPath);
			if(stat.isDirectory() && entry != "node_modules" && entry != ".git") {
				var result = this.findMetaByGuid(fullPath,guid);
				if(result != null) {
					return result;
				}
			} else if(StringTools.endsWith(entry,".meta")) {
				try {
					var content = js_node_Fs.readFileSync(fullPath,{ encoding : "utf-8"});
					var meta = JSON.parse(content);
					if(meta.guid == guid) {
						return meta;
					}
				} catch( _g1 ) {
				}
			}
		}
		return null;
	}
};
var src_main_assets_AssetTypeRegistry = function() {
	this.converters = new haxe_ds_StringMap();
};
src_main_assets_AssetTypeRegistry.__name__ = true;
src_main_assets_AssetTypeRegistry.prototype = {
	register: function(converter) {
		var _g = 0;
		var _g1 = converter.supportedExtensions;
		while(_g < _g1.length) {
			var ext = _g1[_g];
			++_g;
			var normalizedExt = ext.toLowerCase();
			if(!StringTools.startsWith(normalizedExt,".")) {
				normalizedExt = "." + normalizedExt;
			}
			this.converters.h[normalizedExt] = converter;
		}
	}
	,getConverter: function(filePath) {
		var ext = js_node_Path.extname(filePath).toLowerCase();
		return this.converters.h[ext];
	}
	,getAllSupportedExtensions: function() {
		var extensions = [];
		var h = this.converters.h;
		var ext_h = h;
		var ext_keys = Object.keys(h);
		var ext_length = ext_keys.length;
		var ext_current = 0;
		while(ext_current < ext_length) {
			var ext = ext_keys[ext_current++];
			extensions.push(ext);
		}
		return extensions;
	}
};
var src_main_assets_converters_ImageConverter = function() {
	this.supportedExtensions = [".png",".jpg",".jpeg",".webp",".tga",".bmp"];
};
src_main_assets_converters_ImageConverter.__name__ = true;
src_main_assets_converters_ImageConverter.prototype = {
	convert: function(sourcePath,meta) {
		return new Promise(async (resolve, reject) => {
            try {
                const sharp = require('sharp');
                const fs = require('fs');
                const path = require('path');
                
                // Убеждаемся, что папка Build существует
                const buildDir = path.dirname(meta.buildPath);
                if (!fs.existsSync(buildDir)) {
                    fs.mkdirSync(buildDir, { recursive: true });
                }
                
                let pipeline = sharp(sourcePath);
                
                // Применяем настройки из .meta
                const settings = meta.settings || {};
                
                // Resize если указан maxSize
                if (settings.maxSize) {
                    pipeline = pipeline.resize(settings.maxSize, settings.maxSize, { 
                        fit: 'inside', 
                        withoutEnlargement: true 
                    });
                }
                
                // Формат вывода (по умолчанию webp)
                const format = settings.format || 'webp';
                const quality = settings.quality || 80;
                
                if (format === 'webp') {
                    pipeline = pipeline.webp({ quality: quality });
                } else if (format === 'png') {
                    pipeline = pipeline.png({ compressionLevel: 9 });
                } else if (format === 'jpeg' || format === 'jpg') {
                    pipeline = pipeline.jpeg({ quality: quality });
                }
                
                // Сохраняем результат
                await pipeline.toFile(meta.buildPath);
                
                // Получаем метаданные выходного файла
                const outputMeta = await sharp(meta.buildPath).metadata();
                
                resolve({
                    buildPath: meta.buildPath,
                    metadata: {
                        width: outputMeta.width,
                        height: outputMeta.height,
                        format: outputMeta.format,
                        size: fs.statSync(meta.buildPath).size,
                        channels: outputMeta.channels
                    }
                });
                
            } catch (err) {
                reject(err);
            }
        });
	}
};
var src_main_lsp_HaxeLanguageServerManager = function() {
};
src_main_lsp_HaxeLanguageServerManager.__name__ = true;
var src_main_services_ServiceLocator = function() {
};
src_main_services_ServiceLocator.__name__ = true;
src_main_services_ServiceLocator.get = function() {
	if(src_main_services_ServiceLocator._instance == null) {
		src_main_services_ServiceLocator._instance = new src_main_services_ServiceLocator();
	}
	return src_main_services_ServiceLocator._instance;
};
src_main_services_ServiceLocator.init = function() {
	var loc = src_main_services_ServiceLocator.get();
	var registry = new src_main_assets_AssetTypeRegistry();
	registry.register(new src_main_assets_converters_ImageConverter());
	loc.assetPipeline = new src_main_assets_AssetPipelineService(registry);
	loc.lspManager = new src_main_lsp_HaxeLanguageServerManager();
	console.log("src/main/services/ServiceLocator.hx:31:","✅ [ServiceLocator] Main Process services ready");
};
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
ElectronMain.main();
})({});

//# sourceMappingURL=main.js.map