// Generated by Haxe 4.3.6
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var AutoWindow = function() { };
AutoWindow.__name__ = true;
AutoWindow.start = function(overrides) {
	AutoWindow.cfg = AutoWindow.loadPackageConfig();
	console.log("AutoWindow.hx:43:",AutoWindow.cfg);
	AutoWindow.applyDefaults();
	console.log("AutoWindow.hx:46:",AutoWindow.cfg);
	if(overrides != null) {
		if(overrides.width != null) {
			AutoWindow.cfg.width = overrides.width;
		}
		if(overrides.height != null) {
			AutoWindow.cfg.height = overrides.height;
		}
		if(overrides.minWidth != null) {
			AutoWindow.cfg.minWidth = overrides.minWidth;
		}
		if(overrides.minHeight != null) {
			AutoWindow.cfg.minHeight = overrides.minHeight;
		}
		if(overrides.title != null) {
			AutoWindow.cfg.title = overrides.title;
		}
		if(overrides.icon != null) {
			AutoWindow.cfg.icon = overrides.icon;
		}
		if(overrides.show != null) {
			AutoWindow.cfg.show = overrides.show;
		}
		if(overrides.frame != null) {
			AutoWindow.cfg.frame = overrides.frame;
		}
		if(overrides.x != null) {
			AutoWindow.cfg.x = overrides.x;
		}
		if(overrides.y != null) {
			AutoWindow.cfg.y = overrides.y;
		}
		if(overrides.url != null) {
			AutoWindow.cfg.url = overrides.url;
		}
		if(overrides.onReady != null) {
			AutoWindow.cfg.onReady = overrides.onReady;
		}
		if(overrides.onClose != null) {
			AutoWindow.cfg.onClose = overrides.onClose;
		}
	}
	console.log("AutoWindow.hx:63:",AutoWindow.cfg);
	electron_main_App.whenReady().then(function(_) {
		AutoWindow.createWindow();
		AutoWindow.setupLifecycle();
		AutoWindow.setupIpc();
		if(AutoWindow.cfg.onReady != null) {
			AutoWindow.cfg.onReady();
		}
	});
};
AutoWindow.loadPackageConfig = function() {
	try {
		var pkgPath = js_node_Path.join(__dirname,"package.json");
		var pkg = JSON.parse(js_node_Fs.readFileSync(pkgPath,{ encoding : "utf8"}));
		var win = pkg.window != null ? pkg.window : { };
		return { width : win.width, height : win.height, minWidth : win.min_width, minHeight : win.min_height, title : win.title, icon : win.icon, show : win.show, frame : win.frame, x : win.x, y : win.y, url : win.url};
	} catch( _g ) {
		return { };
	}
};
AutoWindow.applyDefaults = function() {
	if(AutoWindow.cfg.width == null) {
		AutoWindow.cfg.width = 1200;
	}
	if(AutoWindow.cfg.height == null) {
		AutoWindow.cfg.height = 800;
	}
	if(AutoWindow.cfg.title == null) {
		AutoWindow.cfg.title = "HIDE IDE";
	}
	if(AutoWindow.cfg.url == null) {
		AutoWindow.cfg.url = "app-electron.html";
	}
	if(AutoWindow.cfg.show == null) {
		AutoWindow.cfg.show = true;
	}
	if(AutoWindow.cfg.frame == null) {
		AutoWindow.cfg.frame = false;
	}
};
AutoWindow.createWindow = function() {
	var opts = { width : AutoWindow.cfg.width, height : AutoWindow.cfg.height, minWidth : AutoWindow.cfg.minWidth, minHeight : AutoWindow.cfg.minHeight, title : AutoWindow.cfg.title, show : false, frame : false, titleBarStyle : "hidden", webPreferences : { nodeIntegration : true, contextIsolation : false, enableRemoteModule : true}};
	if(AutoWindow.cfg.icon != null) {
		opts.icon = js_node_Path.join(__dirname,AutoWindow.cfg.icon);
	}
	if(AutoWindow.cfg.x != null && AutoWindow.cfg.y != null) {
		opts.x = AutoWindow.cfg.x;
		opts.y = AutoWindow.cfg.y;
	}
	AutoWindow.window = new electron_main_BrowserWindow(opts);
	AutoWindow.window.loadFile(AutoWindow.cfg.url);
	AutoWindow.window.on("ready-to-show",function() {
		if(AutoWindow.cfg.show) {
			AutoWindow.window.show();
		}
		AutoWindow.window.focus();
	});
	AutoWindow.window.on("close",function(_) {
		if(AutoWindow.cfg.onClose != null) {
			AutoWindow.cfg.onClose();
		}
	});
};
AutoWindow.setupLifecycle = function() {
	electron_main_App.on("window-all-closed",function() {
		if(Sys.systemName() != "Mac") {
			electron_main_App.quit();
		}
	});
	electron_main_App.on("activate",function() {
		if(electron_main_BrowserWindow.getAllWindows().length == 0) {
			AutoWindow.createWindow();
		}
	});
};
AutoWindow.ensureDirectoryExists = function(dir) {
	if(dir == null || dir == "") {
		return;
	}
	if(js_node_Fs.existsSync(dir)) {
		return;
	}
	AutoWindow.ensureDirectoryExists(js_node_Path.dirname(dir));
	js_node_Fs.mkdirSync(dir);
};
AutoWindow.processMenuTemplate = function(items,sender) {
	if(items == null) {
		return [];
	}
	var result = [];
	var _g = 0;
	while(_g < items.length) {
		var item = items[_g];
		++_g;
		if(item.label == null && item.type != "separator") {
			continue;
		}
		var processed = { label : item.label, type : item.type != null ? item.type : null, enabled : item.enabled != false, submenu : item.submenu != null ? AutoWindow.processMenuTemplate(item.submenu,sender) : null};
		if(item.id != null) {
			var itemId = [item.id];
			processed.click = (function(itemId) {
				return function(menuItem,browserWindow,event) {
					console.log("AutoWindow.hx:192:","[AutoWindow] 🖱 Click: '" + itemId[0] + "'");
					sender.send("menu:click",{ id : itemId[0]});
				};
			})(itemId);
		}
		result.push(processed);
	}
	return result;
};
AutoWindow.setupIpc = function() {
	electron_main_IpcMain.on("app:quit",function(event) {
		electron_main_App.quit();
	});
	electron_main_IpcMain.on("app:reload",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.reload();
		}
	});
	electron_main_IpcMain.on("fs:exists",function(event,filePath) {
		try {
			event.returnValue = js_node_Fs.existsSync(filePath);
		} catch( _g ) {
			event.returnValue = false;
		}
	});
	electron_main_IpcMain.on("fs:readText",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var content = js_node_Fs.readFileSync(filePath,{ encoding : "utf-8"});
				event.returnValue = { content : content};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:readBinary",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var buffer = js_node_Fs.readFileSync(filePath);
				var base64 = buffer.toString("base64");
				event.returnValue = { data : base64};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:writeText",function(event,data) {
		try {
			var dir = js_node_Path.dirname(data.path);
			if(!js_node_Fs.existsSync(dir)) {
				AutoWindow.ensureDirectoryExists(dir);
			}
			js_node_Fs.writeFileSync(data.path,data.content,{ encoding : "utf-8"});
			event.returnValue = { };
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:listFiles",function(event,data) {
		try {
			var files = [];
			var scan = null;
			scan = function(dir) {
				var entries = js_node_Fs.readdirSync(dir);
				var _g = 0;
				while(_g < entries.length) {
					var entry = entries[_g];
					++_g;
					var fullPath = js_node_Path.join(dir,entry);
					var stat = js_node_Fs.statSync(fullPath);
					if(stat.isDirectory() && data.recursive) {
						scan(fullPath);
					} else if(stat.isFile()) {
						files.push(fullPath);
					}
				}
			};
			if(js_node_Fs.existsSync(data.path)) {
				scan(data.path);
			}
			event.returnValue = { files : files};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("app:getAppDataPath",function(event) {
		event.returnValue = electron_main_App.getPath("userData");
	});
	electron_main_IpcMain.handle("dialog:showOpen",function(event,options) {
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showSave",function(event,options) {
		return electron_main_Dialog.showSaveDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showDirectory",function(event,options) {
		options.properties = ["openDirectory","createDirectory"];
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.on("window:setTitle",function(event,title) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setTitle(title);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:enterFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(true);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:maximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.maximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:minimize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.minimize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:unmaximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.unmaximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:leaveFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(false);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("menu:build",function(event,menuData) {
		console.log("AutoWindow.hx:338:","[AutoWindow] 📥 Received menu data");
		var template = AutoWindow.processMenuTemplate(menuData,event.sender);
		var menu = electron_main_Menu.buildFromTemplate(template);
		electron_main_Menu.setApplicationMenu(menu);
		console.log("AutoWindow.hx:342:","[AutoWindow] ✅ Menu set (" + template.length + " top-level items)");
	});
	electron_main_IpcMain.on("window:open",function(event,data) {
		var url = data.url;
		if(url.indexOf("?subView=") != -1) {
			console.log("AutoWindow.hx:350:","[AutoWindow] ⚠️ Sub-view request: " + url);
			event.sender.send("window:open:subview",{ url : url});
			return;
		}
		var opts = { width : data.options.width != null ? data.options.width : 800, height : data.options.height != null ? data.options.height : 600, title : data.options.title != null ? data.options.title : "Hide", parent : AutoWindow.window, webPreferences : { nodeIntegration : true, contextIsolation : false}};
		var child = new electron_main_BrowserWindow(opts);
		child.loadFile(url);
	});
};
var ElectronMain = function() { };
ElectronMain.__name__ = true;
ElectronMain.main = function() {
	AutoWindow.start({ onReady : ElectronMain.startup});
};
ElectronMain.startup = function() {
	console.log("ElectronMain.hx:21:","🚀 ElectronMain: Startup complete");
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var Sys = function() { };
Sys.__name__ = true;
Sys.systemName = function() {
	var _g = process.platform;
	switch(_g) {
	case "darwin":
		return "Mac";
	case "freebsd":
		return "BSD";
	case "linux":
		return "Linux";
	case "win32":
		return "Windows";
	default:
		var other = _g;
		return other;
	}
};
var electron_main_App = require("electron").app;
var electron_main_BrowserWindow = require("electron").BrowserWindow;
var electron_main_Dialog = require("electron").dialog;
var electron_main_IpcMain = require("electron").ipcMain;
var electron_main_Menu = require("electron").Menu;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_node_Fs = require("fs");
var js_node_Path = require("path");
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
ElectronMain.main();
})({});

//# sourceMappingURL=main.js.map