// Generated by Haxe 4.3.6
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var AutoWindow = function() { };
AutoWindow.__name__ = true;
AutoWindow.start = function(overrides) {
	AutoWindow.cfg = AutoWindow.loadPackageConfig();
	console.log("AutoWindow.hx:43:",AutoWindow.cfg);
	AutoWindow.applyDefaults();
	console.log("AutoWindow.hx:46:",AutoWindow.cfg);
	if(overrides != null) {
		if(overrides.width != null) {
			AutoWindow.cfg.width = overrides.width;
		}
		if(overrides.height != null) {
			AutoWindow.cfg.height = overrides.height;
		}
		if(overrides.minWidth != null) {
			AutoWindow.cfg.minWidth = overrides.minWidth;
		}
		if(overrides.minHeight != null) {
			AutoWindow.cfg.minHeight = overrides.minHeight;
		}
		if(overrides.title != null) {
			AutoWindow.cfg.title = overrides.title;
		}
		if(overrides.icon != null) {
			AutoWindow.cfg.icon = overrides.icon;
		}
		if(overrides.show != null) {
			AutoWindow.cfg.show = overrides.show;
		}
		if(overrides.frame != null) {
			AutoWindow.cfg.frame = overrides.frame;
		}
		if(overrides.x != null) {
			AutoWindow.cfg.x = overrides.x;
		}
		if(overrides.y != null) {
			AutoWindow.cfg.y = overrides.y;
		}
		if(overrides.url != null) {
			AutoWindow.cfg.url = overrides.url;
		}
		if(overrides.onReady != null) {
			AutoWindow.cfg.onReady = overrides.onReady;
		}
		if(overrides.onClose != null) {
			AutoWindow.cfg.onClose = overrides.onClose;
		}
	}
	console.log("AutoWindow.hx:63:",AutoWindow.cfg);
	electron_main_App.whenReady().then(function(_) {
		AutoWindow.createWindow();
		AutoWindow.setupLifecycle();
		AutoWindow.setupIpc();
		if(AutoWindow.cfg.onReady != null) {
			AutoWindow.cfg.onReady();
		}
	});
};
AutoWindow.loadPackageConfig = function() {
	try {
		var pkgPath = js_node_Path.join(__dirname,"package.json");
		var pkg = JSON.parse(js_node_Fs.readFileSync(pkgPath,{ encoding : "utf8"}));
		var win = pkg.window != null ? pkg.window : { };
		return { width : win.width, height : win.height, minWidth : win.min_width, minHeight : win.min_height, title : win.title, icon : win.icon, show : win.show, frame : win.frame, x : win.x, y : win.y, url : win.url};
	} catch( _g ) {
		return { };
	}
};
AutoWindow.applyDefaults = function() {
	if(AutoWindow.cfg.width == null) {
		AutoWindow.cfg.width = 1200;
	}
	if(AutoWindow.cfg.height == null) {
		AutoWindow.cfg.height = 800;
	}
	if(AutoWindow.cfg.title == null) {
		AutoWindow.cfg.title = "HIDE IDE";
	}
	if(AutoWindow.cfg.url == null) {
		AutoWindow.cfg.url = "app-electron.html";
	}
	if(AutoWindow.cfg.show == null) {
		AutoWindow.cfg.show = true;
	}
	if(AutoWindow.cfg.frame == null) {
		AutoWindow.cfg.frame = false;
	}
};
AutoWindow.createWindow = function() {
	var opts = { width : AutoWindow.cfg.width, height : AutoWindow.cfg.height, minWidth : AutoWindow.cfg.minWidth, minHeight : AutoWindow.cfg.minHeight, title : AutoWindow.cfg.title, show : false, frame : false, titleBarStyle : "hidden", webPreferences : { nodeIntegration : true, contextIsolation : false, enableRemoteModule : true, preload : js_node_Path.join(__dirname,"preload.js")}};
	if(AutoWindow.cfg.icon != null) {
		opts.icon = js_node_Path.join(__dirname,AutoWindow.cfg.icon);
	}
	if(AutoWindow.cfg.x != null && AutoWindow.cfg.y != null) {
		opts.x = AutoWindow.cfg.x;
		opts.y = AutoWindow.cfg.y;
	}
	AutoWindow.window = new electron_main_BrowserWindow(opts);
	AutoWindow.window.loadFile(AutoWindow.cfg.url);
	AutoWindow.window.on("ready-to-show",function() {
		if(AutoWindow.cfg.show) {
			AutoWindow.window.show();
		}
		AutoWindow.window.focus();
	});
	AutoWindow.window.on("close",function(_) {
		if(AutoWindow.cfg.onClose != null) {
			AutoWindow.cfg.onClose();
		}
	});
};
AutoWindow.setupLifecycle = function() {
	electron_main_App.on("window-all-closed",function() {
		if(Sys.systemName() != "Mac") {
			electron_main_App.quit();
		}
	});
	electron_main_App.on("activate",function() {
		if(electron_main_BrowserWindow.getAllWindows().length == 0) {
			AutoWindow.createWindow();
		}
	});
};
AutoWindow.ensureDirectoryExists = function(dir) {
	if(dir == null || dir == "") {
		return;
	}
	if(js_node_Fs.existsSync(dir)) {
		return;
	}
	AutoWindow.ensureDirectoryExists(js_node_Path.dirname(dir));
	js_node_Fs.mkdirSync(dir);
};
AutoWindow.processMenuTemplate = function(items,sender) {
	if(items == null) {
		return [];
	}
	var result = [];
	var _g = 0;
	while(_g < items.length) {
		var item = items[_g];
		++_g;
		if(item.label == null && item.type != "separator") {
			continue;
		}
		var processed = { label : item.label, type : item.type != null ? item.type : null, enabled : item.enabled != false, submenu : item.submenu != null ? AutoWindow.processMenuTemplate(item.submenu,sender) : null};
		if(item.id != null) {
			var itemId = [item.id];
			processed.click = (function(itemId) {
				return function(menuItem,browserWindow,event) {
					console.log("AutoWindow.hx:193:","[AutoWindow] 🖱 Click: '" + itemId[0] + "'");
					sender.send("menu:click",{ id : itemId[0]});
				};
			})(itemId);
		}
		result.push(processed);
	}
	return result;
};
AutoWindow.setupIpc = function() {
	electron_main_IpcMain.handle("lsp:start",function(event,rootPath) {
		HaxeLanguageServerManager.start(rootPath);
		HaxeLanguageServerManager.initialize();
		return { success : true};
	});
	electron_main_IpcMain.handle("lsp:stop",function(event) {
		HaxeLanguageServerManager.stop();
		return { success : true};
	});
	electron_main_IpcMain.handle("lsp:request",function(event,data) {
		var id = HaxeLanguageServerManager.sendRequest(data.method,data.params);
		return { id : id};
	});
	electron_main_IpcMain.on("lsp:notification",function(event,data) {
		HaxeLanguageServerManager.sendNotification(data.method,data.params);
		event.returnValue = null;
	});
	electron_main_IpcMain.on("lsp:response",function(event,data) {
		HaxeLanguageServerManager.sendResponse(data.id,data.result);
		event.returnValue = null;
	});
	electron_main_IpcMain.on("lsp:didSave",function(event,data) {
		HaxeLanguageServerManager.didSave(data.uri,data.text);
		event.returnValue = null;
	});
	electron_main_IpcMain.on("lsp:didOpen",function(event,data) {
		HaxeLanguageServerManager.sendNotification("textDocument/didOpen",{ textDocument : { uri : data.uri, languageId : data.languageId, version : data.version, text : data.text}});
		event.returnValue = null;
	});
	electron_main_IpcMain.on("lsp:didChange",function(event,data) {
		HaxeLanguageServerManager.sendNotification("textDocument/didChange",{ textDocument : { uri : data.uri, version : data.version}, contentChanges : data.contentChanges});
		event.returnValue = null;
	});
	electron_main_IpcMain.on("lsp:didClose",function(event,data) {
		HaxeLanguageServerManager.sendNotification("textDocument/didClose",{ textDocument : { uri : data.uri}});
		event.returnValue = null;
	});
	electron_main_IpcMain.handle("lsp:completion",function(event,data) {
		return new Promise(function(resolve,reject) {
			HaxeLanguageServerManager.sendRequest("textDocument/completion",{ textDocument : { uri : data.uri}, position : { line : data.line, character : data.character}, context : data.context},function(result) {
				resolve(result);
			});
		});
	});
	electron_main_IpcMain.handle("lsp:hover",function(event,data) {
		return new Promise(function(resolve,reject) {
			HaxeLanguageServerManager.sendRequest("textDocument/hover",{ textDocument : { uri : data.uri}, position : { line : data.line, character : data.character}},function(result) {
				resolve(result);
			});
		});
	});
	electron_main_IpcMain.handle("lsp:definition",function(event,data) {
		return new Promise(function(resolve,reject) {
			HaxeLanguageServerManager.sendRequest("textDocument/definition",{ textDocument : { uri : data.uri}, position : { line : data.line, character : data.character}},function(result) {
				resolve(result);
			});
		});
	});
	electron_main_IpcMain.on("app:quit",function(event) {
		electron_main_App.quit();
	});
	electron_main_IpcMain.on("app:reload",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.reload();
		}
	});
	electron_main_IpcMain.on("fs:exists",function(event,filePath) {
		try {
			event.returnValue = js_node_Fs.existsSync(filePath);
		} catch( _g ) {
			event.returnValue = false;
		}
	});
	electron_main_IpcMain.on("fs:readText",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var content = js_node_Fs.readFileSync(filePath,{ encoding : "utf-8"});
				event.returnValue = { content : content};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:readBinary",function(event,filePath) {
		try {
			if(!js_node_Fs.existsSync(filePath)) {
				event.returnValue = { error : "File not found"};
			} else {
				var buffer = js_node_Fs.readFileSync(filePath);
				var base64 = buffer.toString("base64");
				event.returnValue = { data : base64};
			}
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:writeText",function(event,data) {
		try {
			var dir = js_node_Path.dirname(data.path);
			if(!js_node_Fs.existsSync(dir)) {
				AutoWindow.ensureDirectoryExists(dir);
			}
			js_node_Fs.writeFileSync(data.path,data.content,{ encoding : "utf-8"});
			event.returnValue = { };
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("fs:listFiles",function(event,data) {
		try {
			var files = [];
			var scan = null;
			scan = function(dir) {
				var entries = js_node_Fs.readdirSync(dir);
				var _g = 0;
				while(_g < entries.length) {
					var entry = entries[_g];
					++_g;
					var fullPath = js_node_Path.join(dir,entry);
					var stat = js_node_Fs.statSync(fullPath);
					if(stat.isDirectory() && data.recursive) {
						scan(fullPath);
					} else if(stat.isFile()) {
						files.push(fullPath);
					}
				}
			};
			if(js_node_Fs.existsSync(data.path)) {
				scan(data.path);
			}
			event.returnValue = { files : files};
		} catch( _g ) {
			var e = haxe_Exception.caught(_g).unwrap();
			event.returnValue = { error : Std.string(e)};
		}
	});
	electron_main_IpcMain.on("app:getAppDataPath",function(event) {
		event.returnValue = electron_main_App.getPath("userData");
	});
	electron_main_IpcMain.handle("dialog:showOpen",function(event,options) {
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showSave",function(event,options) {
		return electron_main_Dialog.showSaveDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.handle("dialog:showDirectory",function(event,options) {
		options.properties = ["openDirectory","createDirectory"];
		return electron_main_Dialog.showOpenDialog(AutoWindow.window,options);
	});
	electron_main_IpcMain.on("window:setTitle",function(event,title) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setTitle(title);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:enterFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(true);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:maximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.maximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:minimize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.minimize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:unmaximize",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.unmaximize();
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("window:leaveFullscreen",function(event) {
		if(AutoWindow.window != null) {
			AutoWindow.window.setFullScreen(false);
		}
		event.returnValue = null;
	});
	electron_main_IpcMain.on("menu:build",function(event,menuData) {
		console.log("AutoWindow.hx:450:","[AutoWindow] 📥 Received menu data");
		var template = AutoWindow.processMenuTemplate(menuData,event.sender);
		var menu = electron_main_Menu.buildFromTemplate(template);
		electron_main_Menu.setApplicationMenu(menu);
		console.log("AutoWindow.hx:454:","[AutoWindow] ✅ Menu set (" + template.length + " top-level items)");
	});
	electron_main_IpcMain.handle("lsp:semanticTokensFull",function(event,data) {
		return new Promise(function(resolve,reject) {
			HaxeLanguageServerManager.sendRequest("textDocument/semanticTokens/full",{ textDocument : { uri : data.uri}},function(result) {
				resolve(result);
			});
		});
	});
	electron_main_IpcMain.handle("lsp:semanticTokensRange",function(event,data) {
		return new Promise(function(resolve,reject) {
			HaxeLanguageServerManager.sendRequest("textDocument/semanticTokens/range",{ textDocument : { uri : data.uri}, range : data.range},function(result) {
				resolve(result);
			});
		});
	});
	electron_main_IpcMain.handle("lsp:semanticTokensLegend",function(event) {
		return new Promise(function(resolve,reject) {
			resolve(HaxeLanguageServerManager.getSemanticTokensLegend());
		});
	});
	electron_main_IpcMain.on("window:open",function(event,data) {
		var url = data.url;
		if(url.indexOf("?subView=") != -1) {
			console.log("AutoWindow.hx:491:","[AutoWindow] ⚠️ Sub-view request: " + url);
			event.sender.send("window:open:subview",{ url : url});
			return;
		}
		var opts = { width : data.options.width != null ? data.options.width : 800, height : data.options.height != null ? data.options.height : 600, title : data.options.title != null ? data.options.title : "Hide", parent : AutoWindow.window, webPreferences : { nodeIntegration : true, contextIsolation : false, preload : js_node_Path.join(__dirname,"preload.js")}};
		var child = new electron_main_BrowserWindow(opts);
		child.loadFile(url);
	});
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = true;
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw haxe_Exception.thrown("EReg::matched");
		}
	}
};
var ElectronMain = function() { };
ElectronMain.__name__ = true;
ElectronMain.main = function() {
	AutoWindow.start({ onReady : ElectronMain.startup});
};
ElectronMain.startup = function() {
	console.log("ElectronMain.hx:21:","🚀 ElectronMain: Startup complete");
};
var HaxeLanguageServerManager = function() { };
HaxeLanguageServerManager.__name__ = true;
HaxeLanguageServerManager.start = function(rootPath) {
	if(HaxeLanguageServerManager.isStarted) {
		console.log("HaxeLanguageServerManager.hx:32:","⚠️ [LSP] Already started");
		return true;
	}
	HaxeLanguageServerManager.projectRoot = rootPath;
	var serverPath = js_node_Path.join(__dirname,"server.js");
	if(!js_node_Fs.existsSync(serverPath)) {
		console.log("HaxeLanguageServerManager.hx:43:","❌ [LSP] Server not found at: " + serverPath);
		return false;
	}
	console.log("HaxeLanguageServerManager.hx:47:","🚀 [LSP] Starting Haxe Language Server...");
	console.log("HaxeLanguageServerManager.hx:48:","📁 [LSP] Project root: " + rootPath);
	console.log("HaxeLanguageServerManager.hx:49:","📄 [LSP] Server path: " + serverPath);
	HaxeLanguageServerManager.serverProcess = js_node_ChildProcess.spawn("node",[serverPath],{ cwd : rootPath, stdio : ["pipe","pipe","pipe"]});
	HaxeLanguageServerManager.serverProcess.stdout.on("data",function(data) {
		HaxeLanguageServerManager.buffer += Std.string(data);
		while(true) {
			var headerEnd = HaxeLanguageServerManager.buffer.indexOf("\r\n\r\n");
			if(headerEnd == -1) {
				break;
			}
			var header = HaxeLanguageServerManager.buffer.substring(0,headerEnd);
			var headerRegex = new EReg("Content-Length:\\s*(\\d+)","i");
			if(!headerRegex.match(header)) {
				console.log("HaxeLanguageServerManager.hx:75:","❌ [LSP] Invalid header: " + header);
				HaxeLanguageServerManager.buffer = HaxeLanguageServerManager.buffer.substring(headerEnd + 4);
				continue;
			}
			var contentLength = Std.parseInt(headerRegex.matched(1));
			var messageStart = headerEnd + 4;
			var messageEnd = messageStart + contentLength;
			if(HaxeLanguageServerManager.buffer.length < messageEnd) {
				break;
			}
			var message = HaxeLanguageServerManager.buffer.substring(messageStart,messageEnd);
			HaxeLanguageServerManager.buffer = HaxeLanguageServerManager.buffer.substring(messageEnd);
			try {
				var json = JSON.parse(message);
				HaxeLanguageServerManager.handleMessage(json);
			} catch( _g ) {
				var e = haxe_Exception.caught(_g).unwrap();
				console.log("HaxeLanguageServerManager.hx:102:","❌ [LSP] Failed to parse message: " + Std.string(e));
				console.log("HaxeLanguageServerManager.hx:103:","   Message: " + message.substring(0,200));
			}
		}
	});
	HaxeLanguageServerManager.serverProcess.stderr.on("data",function(data) {
		console.log("HaxeLanguageServerManager.hx:110:","[LSP Server] " + data.toString());
	});
	HaxeLanguageServerManager.serverProcess.on("error",function(err) {
		console.log("HaxeLanguageServerManager.hx:115:","❌ [LSP] Server error: " + Std.string(err));
	});
	HaxeLanguageServerManager.serverProcess.on("exit",function(code) {
		console.log("HaxeLanguageServerManager.hx:119:","⚠️ [LSP] Server exited with code: " + code);
		HaxeLanguageServerManager.isStarted = false;
		HaxeLanguageServerManager.isInitialized = false;
	});
	HaxeLanguageServerManager.isStarted = true;
	HaxeLanguageServerManager.initialize();
	console.log("HaxeLanguageServerManager.hx:128:","✅ [LSP] Language Server started");
	return true;
};
HaxeLanguageServerManager.initialize = function() {
	if(!HaxeLanguageServerManager.isStarted || HaxeLanguageServerManager.serverProcess == null) {
		console.log("HaxeLanguageServerManager.hx:138:","❌ [LSP] Cannot initialize: server not started");
		return;
	}
	var rootPathNormalized = HaxeLanguageServerManager.projectRoot.split("\\").join("/");
	var rootUri = rootPathNormalized.charAt(0) == "/" ? "file://" + rootPathNormalized : "file:///" + rootPathNormalized;
	var params = { processId : process.pid, rootUri : rootUri, capabilities : { textDocument : { completion : { completionItem : { snippetSupport : true, resolveSupport : { properties : ["documentation","detail"]}}}, hover : { contentFormat : ["markdown","plaintext"]}, signatureHelp : { }, definition : { linkSupport : true}, references : { }, documentSymbol : { hierarchicalDocumentSymbolSupport : true}, codeAction : { }, formatting : { }, publishDiagnostics : { relatedInformation : true, tagSupport : { valueSet : [1,2]}}, synchronization : { didSave : true, willSave : false, willSaveWaitUntil : false}, semanticTokens : { requests : { full : true, range : false}, formats : ["relative"], overlappingTokenSupport : false, multilineTokenSupport : false, serverCancelSupport : false, augmentsSyntaxTokens : true}}, workspace : { applyEdit : true, configuration : true, didChangeConfiguration : { dynamicRegistration : true}}}, initializationOptions : { displayServerConfig : { path : "haxe", env : { }, 'arguments' : [], print : { completion : false, reusing : false}, useSocket : true}, displayArguments : [], haxelibConfig : { executable : "haxelib"}, sendMethodResults : false, experimentalClientCapabilities : { supportedCommands : []}}};
	HaxeLanguageServerManager.sendRequest("initialize",params,function(result) {
		console.log("HaxeLanguageServerManager.hx:217:","✅ [LSP] Initialize response received");
		if(result != null && result.capabilities != null) {
			var caps = result.capabilities;
			if(Object.prototype.hasOwnProperty.call(caps,"semanticTokensProvider") && caps.semanticTokensProvider != null) {
				var provider = caps.semanticTokensProvider;
				if(provider.legend != null) {
					console.log("HaxeLanguageServerManager.hx:226:","✅ [LSP] Semantic tokens SUPPORTED!");
					HaxeLanguageServerManager.semanticTokensLegend = provider.legend;
				}
			} else {
				console.log("HaxeLanguageServerManager.hx:230:","⚠️ [LSP] Semantic tokens NOT supported by server");
				console.log("HaxeLanguageServerManager.hx:231:","   Available capabilities: " + JSON.stringify(Reflect.fields(caps)));
			}
		}
		HaxeLanguageServerManager.sendNotification("initialized",{ });
		HaxeLanguageServerManager.sendConfiguration();
		HaxeLanguageServerManager.isInitialized = true;
		console.log("HaxeLanguageServerManager.hx:242:","✅ [LSP] Initialized notification sent");
	});
};
HaxeLanguageServerManager.sendConfiguration = function() {
	var settings = { settings : { haxe : { enableCodeLens : false, enableDiagnostics : true, enableServerView : false, enableSignatureHelpDocumentation : true, diagnosticsOnFileOpen : true, diagnosticsForAllOpenFiles : true, diagnosticsPathFilter : "${workspaceRoot}", displayHost : null, displayPort : null, buildCompletionCache : true, enableCompletionCacheWarning : true, useLegacyCompletion : false, useLegacyDiagnostics : false, codeGeneration : { functions : { anonymous : { argumentTypeHints : false, returnTypeHint : "never", useArrowSyntax : true, placeOpenBraceOnNewLine : false, explicitPublic : false, explicitPrivate : false, explicitNull : false}, field : { argumentTypeHints : true, returnTypeHint : "non-void", useArrowSyntax : false, placeOpenBraceOnNewLine : false, explicitPublic : false, explicitPrivate : false, explicitNull : false}}, imports : { style : "type", enableAutoImports : true}, "switch" : { parentheses : false}}, exclude : ["zpp_nape"], postfixCompletion : { level : "full"}, importsSortOrder : "all-alphabetical", maxCompletionItems : 1000, renameSourceFolders : ["src","source","Source","test","tests"], disableRefactorCache : false, disableInlineValue : true, inlayHints : { variableTypes : false, parameterNames : false, parameterTypes : false, functionReturnTypes : false, conditionals : false}, serverRecording : { enabled : false, path : ".haxelsp/recording/", exclude : [], excludeUntracked : false, watch : []}}}};
	HaxeLanguageServerManager.sendNotification("workspace/didChangeConfiguration",settings);
	console.log("HaxeLanguageServerManager.hx:320:","✅ [LSP] Configuration sent");
};
HaxeLanguageServerManager.stop = function() {
	if(HaxeLanguageServerManager.serverProcess != null) {
		HaxeLanguageServerManager.sendRequest("shutdown",{ },function(_) {
			HaxeLanguageServerManager.sendNotification("exit",{ });
			haxe_Timer.delay(function() {
				if(HaxeLanguageServerManager.serverProcess != null) {
					HaxeLanguageServerManager.serverProcess.kill();
					HaxeLanguageServerManager.serverProcess = null;
				}
				HaxeLanguageServerManager.isStarted = false;
				HaxeLanguageServerManager.isInitialized = false;
				HaxeLanguageServerManager.buffer = "";
				HaxeLanguageServerManager.requestId = 0;
				HaxeLanguageServerManager.pendingRequests.h = { };
				console.log("HaxeLanguageServerManager.hx:340:","🛑 [LSP] Language Server stopped");
			},500);
		});
	}
};
HaxeLanguageServerManager.sendRequest = function(method,params,callback) {
	if(HaxeLanguageServerManager.serverProcess == null || !HaxeLanguageServerManager.isStarted) {
		console.log("HaxeLanguageServerManager.hx:352:","❌ [LSP] Server not started");
		if(callback != null) {
			callback(null);
		}
		return -1;
	}
	HaxeLanguageServerManager.requestId++;
	var id = HaxeLanguageServerManager.requestId;
	if(callback != null) {
		HaxeLanguageServerManager.pendingRequests.h[id] = callback;
		haxe_Timer.delay(function() {
			if(HaxeLanguageServerManager.pendingRequests.h.hasOwnProperty(id)) {
				HaxeLanguageServerManager.pendingRequests.remove(id);
				console.log("HaxeLanguageServerManager.hx:368:","⚠️ [LSP] Request " + id + " (" + method + ") timed out");
				callback(null);
			}
		},30000);
	}
	var message = { jsonrpc : "2.0", id : id, method : method, params : params};
	HaxeLanguageServerManager.sendJsonRpc(message);
	return id;
};
HaxeLanguageServerManager.sendNotification = function(method,params) {
	if(HaxeLanguageServerManager.serverProcess == null || !HaxeLanguageServerManager.isStarted) {
		console.log("HaxeLanguageServerManager.hx:391:","❌ [LSP] Server not started");
		return;
	}
	var message = { jsonrpc : "2.0", method : method, params : params};
	HaxeLanguageServerManager.sendJsonRpc(message);
};
HaxeLanguageServerManager.sendResponse = function(id,result) {
	if(HaxeLanguageServerManager.serverProcess == null) {
		return;
	}
	var message = { jsonrpc : "2.0", id : id, result : result};
	HaxeLanguageServerManager.sendJsonRpc(message);
};
HaxeLanguageServerManager.didSave = function(uri,text) {
	HaxeLanguageServerManager.sendNotification("textDocument/didSave",{ textDocument : { uri : uri}});
};
HaxeLanguageServerManager.sendJsonRpc = function(message) {
	var json = JSON.stringify(message);
	var contentLength = js_node_buffer_Buffer.byteLength(json,"utf8");
	var header = "Content-Length: " + contentLength + "\r\n\r\n";
	HaxeLanguageServerManager.serverProcess.stdin.write(header + json);
};
HaxeLanguageServerManager.handleMessage = function(message) {
	if(message.id != null && HaxeLanguageServerManager.pendingRequests.h.hasOwnProperty(message.id)) {
		var callback = HaxeLanguageServerManager.pendingRequests.h[message.id];
		HaxeLanguageServerManager.pendingRequests.remove(message.id);
		if(message.error != null) {
			console.log("HaxeLanguageServerManager.hx:486:","❌ [LSP] Error for request " + Std.string(message.id) + ": " + Std.string(message.error.message));
			if(callback != null) {
				callback({ error : message.error});
			}
		} else if(callback != null) {
			callback(message.result);
		}
		return;
	}
	if(message.id != null && message.method != null) {
		HaxeLanguageServerManager.handleServerRequest(message);
		return;
	}
	if(message.method != null) {
		HaxeLanguageServerManager.handleServerNotification(message);
		return;
	}
};
HaxeLanguageServerManager.handleServerRequest = function(message) {
	console.log("HaxeLanguageServerManager.hx:512:","📨 [LSP] Server request: " + Std.string(message.method));
	switch(message.method) {
	case "client/registerCapability":
		var registrations = message.params.registrations;
		var _g = 0;
		while(_g < registrations.length) {
			var reg = registrations[_g];
			++_g;
			HaxeLanguageServerManager.registeredCapabilities.push(reg);
			console.log("HaxeLanguageServerManager.hx:605:","   ✅ Registered capability: " + Std.string(reg.method));
		}
		HaxeLanguageServerManager.sendResponse(message.id,null);
		break;
	case "window/workDoneProgress/create":
		HaxeLanguageServerManager.sendResponse(message.id,null);
		break;
	case "workspace/configuration":
		var items = message.params.items;
		var result = [];
		var _g = 0;
		while(_g < items.length) {
			var item = items[_g];
			++_g;
			if(item.section == "haxe") {
				result.push({ enableCodeLens : false, enableDiagnostics : true, enableServerView : false, enableSignatureHelpDocumentation : true, diagnosticsOnFileOpen : true, diagnosticsForAllOpenFiles : true, diagnosticsPathFilter : "${workspaceRoot}", displayHost : null, displayPort : null, buildCompletionCache : true, enableCompletionCacheWarning : true, useLegacyCompletion : false, useLegacyDiagnostics : false, codeGeneration : { functions : { anonymous : { argumentTypeHints : false, returnTypeHint : "never", useArrowSyntax : true, placeOpenBraceOnNewLine : false, explicitPublic : false, explicitPrivate : false, explicitNull : false}, field : { argumentTypeHints : true, returnTypeHint : "non-void", useArrowSyntax : false, placeOpenBraceOnNewLine : false, explicitPublic : false, explicitPrivate : false, explicitNull : false}}, imports : { style : "type", enableAutoImports : true}, "switch" : { parentheses : false}}, exclude : ["zpp_nape"], postfixCompletion : { level : "full"}, importsSortOrder : "all-alphabetical", maxCompletionItems : 1000, renameSourceFolders : ["src","source","Source","test","tests"], disableRefactorCache : false, disableInlineValue : true, inlayHints : { variableTypes : false, parameterNames : false, parameterTypes : false, functionReturnTypes : false, conditionals : false}, serverRecording : { enabled : false, path : ".haxelsp/recording/", exclude : [], excludeUntracked : false, watch : []}});
			} else {
				result.push({ });
			}
		}
		HaxeLanguageServerManager.sendResponse(message.id,result);
		console.log("HaxeLanguageServerManager.hx:594:","   ✅ Responded with configuration for " + items.length + " items");
		break;
	default:
		if(AutoWindow.window != null) {
			AutoWindow.window.webContents.send("lsp:server-request",{ id : message.id, method : message.method, params : message.params});
		}
	}
};
HaxeLanguageServerManager.handleServerNotification = function(message) {
	console.log("HaxeLanguageServerManager.hx:626:","📨 [LSP] Server notification: " + Std.string(message.method));
	switch(message.method) {
	case "textDocument/publishDiagnostics":
		if(AutoWindow.window != null) {
			AutoWindow.window.webContents.send("lsp:diagnostics",{ uri : message.params.uri, diagnostics : message.params.diagnostics});
		}
		break;
	case "window/logMessage":
		console.log("HaxeLanguageServerManager.hx:630:","[LSP Log] " + Std.string(message.params.message));
		break;
	case "window/showMessage":
		console.log("HaxeLanguageServerManager.hx:633:","[LSP Message] " + Std.string(message.params.message));
		break;
	default:
		if(AutoWindow.window != null) {
			AutoWindow.window.webContents.send("lsp:notification",{ method : message.method, params : message.params});
		}
	}
};
HaxeLanguageServerManager.getSemanticTokensLegend = function() {
	return HaxeLanguageServerManager.semanticTokensLegend;
};
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) {
			a.push(f);
		}
		}
	}
	return a;
};
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var Sys = function() { };
Sys.__name__ = true;
Sys.systemName = function() {
	var _g = process.platform;
	switch(_g) {
	case "darwin":
		return "Mac";
	case "freebsd":
		return "BSD";
	case "linux":
		return "Linux";
	case "win32":
		return "Windows";
	default:
		var other = _g;
		return other;
	}
};
var electron_main_App = require("electron").app;
var electron_main_BrowserWindow = require("electron").BrowserWindow;
var electron_main_Dialog = require("electron").dialog;
var electron_main_IpcMain = require("electron").ipcMain;
var electron_main_Menu = require("electron").Menu;
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
	,get_native: function() {
		return this.__nativeException;
	}
});
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = true;
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
};
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
});
var haxe_ds_IntMap = function() {
	this.h = { };
};
haxe_ds_IntMap.__name__ = true;
haxe_ds_IntMap.prototype = {
	remove: function(key) {
		if(!this.h.hasOwnProperty(key)) {
			return false;
		}
		delete(this.h[key]);
		return true;
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_node_ChildProcess = require("child_process");
var js_node_Fs = require("fs");
var js_node_Path = require("path");
var js_node_buffer_Buffer = require("buffer").Buffer;
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
HaxeLanguageServerManager.buffer = "";
HaxeLanguageServerManager.isStarted = false;
HaxeLanguageServerManager.isInitialized = false;
HaxeLanguageServerManager.projectRoot = "";
HaxeLanguageServerManager.requestId = 0;
HaxeLanguageServerManager.pendingRequests = new haxe_ds_IntMap();
HaxeLanguageServerManager.registeredCapabilities = [];
ElectronMain.main();
})({});

//# sourceMappingURL=main.js.map